#!/usr/bin/env node
import { spawn, spawnSync } from "node:child_process";
import { createHash } from "node:crypto";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import readline from "node:readline";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const rootDir = resolve(__dirname, "..");
const envPath = resolve(rootDir, ".env");
const envExamplePath = resolve(rootDir, ".env.example");

const args = new Set(process.argv.slice(2));
const assumeYes = args.has("--yes") || args.has("-y");
const skipInstall = args.has("--no-install");
const skipSeed = args.has("--no-seed");
const skipDev = args.has("--no-dev");
const replacePlan = args.has("--replace-plan");
const strictSeed = args.has("--strict-seed");

function log(message = "") {
  console.log(message);
}

function fail(message) {
  console.error(`\n❌ ${message}`);
  process.exit(1);
}

function warn(message) {
  console.warn(`\n⚠️ ${message}`);
}

function run(command, commandArgs, options = {}) {
  const result = spawnSync(command, commandArgs, {
    cwd: rootDir,
    stdio: "inherit",
    shell: process.platform === "win32",
    env: { ...process.env, ...options.env },
  });

  if (result.status !== 0 && options.allowFailure !== true) {
    fail(`${command} ${commandArgs.join(" ")} 执行失败。`);
  }

  return result;
}

function commandExists(command) {
  const checker = process.platform === "win32" ? "where" : "command";
  const checkerArgs = process.platform === "win32" ? [command] : ["-v", command];
  const result = spawnSync(checker, checkerArgs, {
    stdio: "ignore",
    shell: process.platform !== "win32",
  });
  return result.status === 0;
}

function getPackageManager() {
  if (commandExists("pnpm")) return { name: "pnpm", install: ["install"], run: ["run"] };

  if (commandExists("corepack")) {
    log("检测到 corepack，尝试启用 pnpm...");
    spawnSync("corepack", ["enable"], { stdio: "inherit", shell: process.platform === "win32" });
    if (commandExists("pnpm")) return { name: "pnpm", install: ["install"], run: ["run"] };
  }

  if (commandExists("npm")) return { name: "npm", install: ["install"], run: ["run"] };

  fail("未找到 pnpm、corepack 或 npm。请先安装 Node.js 20+。");
}

function installDependencies(pm) {
  const attempts = [
    {
      label: "official npm registry",
      env: {
        npm_config_registry: "https://registry.npmjs.org/",
        NPM_CONFIG_REGISTRY: "https://registry.npmjs.org/",
        npm_config_fetch_retries: "3",
        npm_config_fetch_retry_maxtimeout: "120000",
      },
    },
    {
      label: "npmmirror fallback",
      env: {
        npm_config_registry: "https://registry.npmmirror.com/",
        NPM_CONFIG_REGISTRY: "https://registry.npmmirror.com/",
        npm_config_fetch_retries: "3",
        npm_config_fetch_retry_maxtimeout: "120000",
      },
    },
  ];

  for (const [index, attempt] of attempts.entries()) {
    log(`尝试 ${index + 1}/${attempts.length}：${attempt.label}`);
    const result = run(pm.name, pm.install, { env: attempt.env, allowFailure: true });
    if (result.status === 0) {
      log(`✅ 依赖安装成功（${attempt.label}）`);
      return;
    }
    log(`❌ ${attempt.label} 安装失败，准备切换下一个源...`);
  }

  fail(`${pm.name} ${pm.install.join(" ")} 执行失败。`);
}

function parseEnv(content) {
  const env = {};
  for (const rawLine of content.split(/\r?\n/)) {
    const line = rawLine.trim();
    if (!line || line.startsWith("#")) continue;
    const eq = line.indexOf("=");
    if (eq === -1) continue;
    const key = line.slice(0, eq).trim();
    const value = line.slice(eq + 1).trim();
    env[key] = value;
  }
  return env;
}

function stringifyEnv(env) {
  const orderedKeys = [
    "SUPABASE_URL",
    "SUPABASE_SERVICE_ROLE_KEY",
    "APP_ACCESS_CODE_HASH",
    "APP_TIMEZONE",
    "ALLOW_INSECURE_DEV_COOKIE",
    "AI_API_KEY",
    "AI_MODEL",
    "AI_BASE_URL",
  ];

  const lines = [
    "# Generated by scripts/run-local.mjs",
    "# Supabase service role key and AI key are server-side only. Do not commit .env.",
  ];

  for (const key of orderedKeys) lines.push(`${key}=${env[key] ?? ""}`);
  for (const key of Object.keys(env).sort()) {
    if (!orderedKeys.includes(key)) lines.push(`${key}=${env[key]}`);
  }
  return `${lines.join("\n")}\n`;
}

function mask(value) {
  if (!value) return "未设置";
  if (value.length <= 8) return "已设置";
  return `${value.slice(0, 4)}...${value.slice(-4)}`;
}

function isPlaceholder(value = "") {
  return (
    value.includes("your-project-ref") ||
    value.includes("your-service-role-key") ||
    value.includes("replace-with-generated-hash") ||
    value === "http...e.co"
  );
}

function cleanDefault(value = "") {
  return isPlaceholder(value) ? "" : value;
}

function createQuestionInterface() {
  return readline.createInterface({ input: process.stdin, output: process.stdout });
}

function ask(rl, question, defaultValue = "") {
  if (assumeYes) return Promise.resolve(defaultValue);
  return new Promise((resolvePromise) => {
    rl.question(question, (answer) => resolvePromise(answer.trim() || defaultValue));
  });
}

async function askSecret(question, defaultValue = "") {
  if (assumeYes) return defaultValue;
  return new Promise((resolvePromise) => {
    const stdin = process.stdin;
    const stdout = process.stdout;
    stdout.write(question);
    stdin.setRawMode?.(true);
    stdin.resume();
    stdin.setEncoding("utf8");
    let value = "";

    const onData = (char) => {
      if (char === "\u0003") process.exit(130);
      if (char === "\r" || char === "\n") {
        stdout.write("\n");
        stdin.setRawMode?.(false);
        stdin.pause();
        stdin.removeListener("data", onData);
        resolvePromise(value.trim() || defaultValue);
        return;
      }
      if (char === "\u007f" || char === "\b") {
        value = value.slice(0, -1);
        return;
      }
      value += char;
    };

    stdin.on("data", onData);
  });
}

function sha256AccessCode(accessCode) {
  return `sha256:${createHash("sha256").update(accessCode, "utf8").digest("hex")}`;
}

function hasValidEnv(env) {
  const urlOk = !!env.SUPABASE_URL && !isPlaceholder(env.SUPABASE_URL) && /^https:\/\/.+\.supabase\.co\/?$/.test(env.SUPABASE_URL);
  const keyOk = !!env.SUPABASE_SERVICE_ROLE_KEY && !isPlaceholder(env.SUPABASE_SERVICE_ROLE_KEY);
  const hashOk = /^sha256:[a-f0-9]{64}$/i.test(env.APP_ACCESS_CODE_HASH || "");
  return urlOk && keyOk && hashOk;
}

async function configureEnv() {
  let env = {};
  if (existsSync(envPath)) {
    env = parseEnv(readFileSync(envPath, "utf8"));
  } else if (existsSync(envExamplePath)) {
    env = parseEnv(readFileSync(envExamplePath, "utf8"));
  }

  env.SUPABASE_URL = cleanDefault(env.SUPABASE_URL || "");
  env.SUPABASE_SERVICE_ROLE_KEY = cleanDefault(env.SUPABASE_SERVICE_ROLE_KEY || "");
  if (isPlaceholder(env.APP_ACCESS_CODE_HASH || "")) env.APP_ACCESS_CODE_HASH = "";
  env.APP_TIMEZONE = env.APP_TIMEZONE || "Asia/Shanghai";
  env.ALLOW_INSECURE_DEV_COOKIE = env.ALLOW_INSECURE_DEV_COOKIE || "true";
  env.AI_API_KEY = env.AI_API_KEY || "";
  env.AI_MODEL = env.AI_MODEL || "";
  env.AI_BASE_URL = env.AI_BASE_URL || "";

  log("\nStep 1/4 配置 .env");
  if (hasValidEnv(env)) {
    writeFileSync(envPath, stringifyEnv(env), "utf8");
    log("检测到现有 .env 配置完整，跳过交互配置。");
    log("✅ .env 已准备好");
    return env;
  }

  log("已存在的值可以直接回车保留。\n");

  const rl = createQuestionInterface();
  env.SUPABASE_URL = await ask(
    rl,
    `Supabase Project URL，必填，例如 https://xxxx.supabase.co [${mask(env.SUPABASE_URL)}]: `,
    env.SUPABASE_URL,
  );
  env.SUPABASE_SERVICE_ROLE_KEY = await ask(
    rl,
    `Supabase Service Role Key，必填，不要填 anon key [${mask(env.SUPABASE_SERVICE_ROLE_KEY)}]: `,
    env.SUPABASE_SERVICE_ROLE_KEY,
  );
  rl.close();

  if (!/^sha256:[a-f0-9]{64}$/i.test(env.APP_ACCESS_CODE_HASH || "") && !assumeYes) {
    const accessCode = await askSecret("访问码（留空则继续沿用当前配置）：", "");
    if (accessCode) env.APP_ACCESS_CODE_HASH = sha256AccessCode(accessCode);
  }

  const rl2 = createQuestionInterface();
  env.AI_API_KEY = await ask(rl2, `AI API Key，可留空 [${mask(env.AI_API_KEY)}]: `, env.AI_API_KEY);
  env.AI_MODEL = await ask(rl2, `AI Model，可留空 [${env.AI_MODEL || "未设置"}]: `, env.AI_MODEL);
  env.AI_BASE_URL = await ask(rl2, `AI Base URL，可留空 [${env.AI_BASE_URL || "未设置"}]: `, env.AI_BASE_URL);
  rl2.close();

  if (!env.SUPABASE_URL || !/^https:\/\/.+\.supabase\.co\/?$/.test(env.SUPABASE_URL)) {
    fail("SUPABASE_URL 不正确，请填写 Supabase Project Settings > API 里的 Project URL。");
  }
  if (!env.SUPABASE_SERVICE_ROLE_KEY) {
    fail("SUPABASE_SERVICE_ROLE_KEY 不能为空，请填写 service_role key。");
  }
  if (!/^sha256:[a-f0-9]{64}$/i.test(env.APP_ACCESS_CODE_HASH || "")) {
    fail("APP_ACCESS_CODE_HASH 无效，请先生成访问码哈希，或在交互里输入访问码。");
  }

  writeFileSync(envPath, stringifyEnv(env), "utf8");
  log("✅ .env 已准备好");
  return env;
}

async function main() {
  log("\nHalf Marathon Training App - local runner");
  log("=========================================");

  const nodeMajor = Number(process.versions.node.split(".")[0]);
  if (nodeMajor < 20) {
    fail(`当前 Node.js 版本为 ${process.version}，请升级到 Node.js 20+。`);
  }

  const env = await configureEnv();
  const pm = getPackageManager();

  if (!skipInstall) {
    log(`\nStep 2/4 安装依赖：${pm.name} ${pm.install.join(" ")}`);
    installDependencies(pm);
  } else {
    log("\nStep 2/4 已跳过依赖安装");
  }

  if (!skipSeed) {
    log("\nStep 3/4 执行 seed");
    log("提示：如果这里报表不存在，请先在 Supabase SQL Editor 执行 supabase/migrations 下的 SQL。\n");
    const seedResult = run(pm.name, [...pm.run, "seed"], {
      env: replacePlan ? { SEED_REPLACE_EXISTING_PLAN: "true" } : {},
      allowFailure: true,
    });

    if (seedResult.status === 0) {
      log("✅ seed 执行成功");
    } else if (strictSeed) {
      fail("seed 执行失败，且当前启用了 --strict-seed。");
    } else {
      warn("seed 执行失败，但将继续启动本地服务。若数据未初始化完整，可稍后单独执行 pnpm run seed。");
    }
  } else {
    log("\nStep 3/4 已跳过 seed");
  }

  if (skipDev) {
    log("\nStep 4/4 已跳过开发服务启动");
    log(`如需稍后手动启动，请执行：${pm.name} ${pm.run.join(" ")} dev`);
    return;
  }

  log("\nStep 4/4 启动开发服务");
  log("启动后请访问 http://localhost:3000\n");

  const child = spawn(pm.name, [...pm.run, "dev"], {
    cwd: rootDir,
    stdio: "inherit",
    shell: process.platform === "win32",
    env: { ...process.env, ...env },
  });
  child.on("exit", (code) => process.exit(code ?? 0));
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
