export type WorkoutSeed = {
  week: number;
  dayOffset: number;
  workout_type: string;
  title: string;
  planned_distance_km: number;
  planned_duration_min: number;
  planned_pace_text: string | null;
  planned_pace_seconds_per_km: number | null;
  planned_rpe: number;
  purpose: string;
  warmup: string;
  main_set: string;
  cooldown: string;
  strength_training: boolean;
  notes: string;
};

export type PhaseSeed = {
  phase_name: string;
  start_date: string;
  end_date: string;
  goal: string;
  weekly_mileage_min: number;
  weekly_mileage_max: number;
  training_days: number;
  key_workouts: string;
  test_standard: string;
  ai_notes: string;
};

export const DEFAULT_SEED_START_DATE = "2026-05-25";

export const generatedPlanSourceSummary = {
  "source_file": "deep-research-report.md",
  "source_title": "年底冲击半程马拉松一小时二十一分三十秒的专项训练总方案",
  "default_seed_start_date": "2026-05-25",
  "generated_at": "2026-05-22",
  "phase_count": 7,
  "workout_count": 84,
  "week_summaries": [
    {
      "week": 1,
      "start_date": "2026-05-25",
      "end_date": "2026-05-31",
      "target_range": "24–28 km",
      "seeded_distance_km": 26.0
    },
    {
      "week": 2,
      "start_date": "2026-06-01",
      "end_date": "2026-06-07",
      "target_range": "28–32 km",
      "seeded_distance_km": 30.0
    },
    {
      "week": 3,
      "start_date": "2026-06-08",
      "end_date": "2026-06-14",
      "target_range": "34–37 km",
      "seeded_distance_km": 35.5
    },
    {
      "week": 4,
      "start_date": "2026-06-15",
      "end_date": "2026-06-21",
      "target_range": "28–31 km",
      "seeded_distance_km": 29.5
    },
    {
      "week": 5,
      "start_date": "2026-06-22",
      "end_date": "2026-06-28",
      "target_range": "40–44 km",
      "seeded_distance_km": 42.0
    },
    {
      "week": 6,
      "start_date": "2026-06-29",
      "end_date": "2026-07-05",
      "target_range": "46–50 km",
      "seeded_distance_km": 48.0
    },
    {
      "week": 7,
      "start_date": "2026-07-06",
      "end_date": "2026-07-12",
      "target_range": "50–54 km",
      "seeded_distance_km": 51.9
    },
    {
      "week": 8,
      "start_date": "2026-07-13",
      "end_date": "2026-07-19",
      "target_range": "42–46 km",
      "seeded_distance_km": 44.0
    },
    {
      "week": 9,
      "start_date": "2026-07-20",
      "end_date": "2026-07-26",
      "target_range": "55–58 km",
      "seeded_distance_km": 56.6
    },
    {
      "week": 10,
      "start_date": "2026-07-27",
      "end_date": "2026-08-02",
      "target_range": "59–62 km",
      "seeded_distance_km": 60.4
    },
    {
      "week": 11,
      "start_date": "2026-08-03",
      "end_date": "2026-08-09",
      "target_range": "63–66 km",
      "seeded_distance_km": 64.4
    },
    {
      "week": 12,
      "start_date": "2026-08-10",
      "end_date": "2026-08-16",
      "target_range": "50–55 km",
      "seeded_distance_km": 52.5
    }
  ],
  "notes": "planned_distance_km 是根据每周目标跑量中值和训练时长/训练类型分配得到的结构化计划距离；原文中的距离或时间、配速/RPE 和注意事项均保留在 main_set/notes 中。"
} as const;

export const generatedPhaseTemplates: PhaseSeed[] = [
  {
    "phase_name": "复跑适应期",
    "start_date": "2026-05-25",
    "end_date": "2026-06-21",
    "goal": "恢复跑步频率、组织耐受、基础动作经济性。",
    "weekly_mileage_min": 24,
    "weekly_mileage_max": 36,
    "training_days": 5,
    "key_workouts": "轻松跑、短坡冲 8–12 秒、放松加速跑、60–75 分钟长跑",
    "test_standard": "45 分钟轻松跑完成质量；75 分钟长跑后 24 小时内恢复；无 focal pain",
    "ai_notes": "进入下一阶段标准：能稳定 4–5 跑天/周；无持续胫骨/跟腱/足底晨痛。"
  },
  {
    "phase_name": "基础有氧重建期",
    "start_date": "2026-06-22",
    "end_date": "2026-07-19",
    "goal": "提升低强度容量，建立稳定有氧与长跑惯性。",
    "weekly_mileage_min": 38,
    "weekly_mileage_max": 52,
    "training_days": 6,
    "key_workouts": "轻松跑、稳定有氧块 2×10’→3×10’、80–100 分钟长跑",
    "test_standard": "20 分钟稳态跑；受控五公里测试",
    "ai_notes": "进入下一阶段标准：45–50 km/周可持续；20–24 分钟稳态不失控。"
  },
  {
    "phase_name": "跑量建设期",
    "start_date": "2026-07-20",
    "end_date": "2026-08-16",
    "goal": "把“能跑”变成“能训练”，开始阈值启蒙。",
    "weekly_mileage_min": 52,
    "weekly_mileage_max": 66,
    "training_days": 6,
    "key_workouts": "T-light 4×5’、3×2 km 阈值、100–110 分钟长跑、短加速跑",
    "test_standard": "五公里正式测试",
    "ai_notes": "进入下一阶段标准：55 km 以上周量可承受；五公里开始逼近 21 分钟上下。"
  },
  {
    "phase_name": "阈值能力提升期",
    "start_date": "2026-08-17",
    "end_date": "2026-09-27",
    "goal": "把阈值做成主线，提高可持续速度。",
    "weekly_mileage_min": 60,
    "weekly_mileage_max": 78,
    "training_days": 6,
    "key_workouts": "20–40 分钟总阈值量、巡航间歇、稳态长跑收尾",
    "test_standard": "六公里节奏跑或十公里练习赛",
    "ai_notes": "进入下一阶段标准：30–35 分钟阈值总量可控；长跑后恢复良好。"
  },
  {
    "phase_name": "10km 能力强化期",
    "start_date": "2026-09-28",
    "end_date": "2026-11-01",
    "goal": "提高十公里速度和半马前段速度储备。",
    "weekly_mileage_min": 68,
    "weekly_mileage_max": 84,
    "training_days": 6,
    "key_workouts": "1 km/2 km 重复跑、阈值+十公里交替、坡跑、18–22 km 长跑",
    "test_standard": "十公里比赛或测验",
    "ai_notes": "进入下一阶段标准：十公里必须开始进入 40 分钟附近。"
  },
  {
    "phase_name": "半马专项期",
    "start_date": "2026-11-02",
    "end_date": "2026-12-06",
    "goal": "把阈值、十公里能力转换成半马专项耐力。",
    "weekly_mileage_min": 75,
    "weekly_mileage_max": 92,
    "training_days": 6,
    "key_workouts": "3×4 km、2×5 km、进阶至 2×6 km 的半马专项段；20–24 km 渐进长跑",
    "test_standard": "十五公里或关键专项课",
    "ai_notes": "进入下一阶段标准：能完成中长段专项配速训练且次日不崩。"
  },
  {
    "phase_name": "赛前调整期",
    "start_date": "2026-12-07",
    "end_date": "2026-12-31",
    "goal": "降疲劳、保强度、把状态推向年底临时主赛窗口。",
    "weekly_mileage_min": 28,
    "weekly_mileage_max": 65,
    "training_days": 6,
    "key_workouts": "维持阈值感和配速感，不再扩大量；赛前三周约为峰值的 60–70% / 45–55% / 30–40%",
    "test_standard": "3 km 小测或轻锐化",
    "ai_notes": "目标比赛未设置时，系统暂按 2026-12-31 作为长期规划终点，但目标页仍显示“目标比赛暂未设置”。"
  }
];

export const generatedWorkoutTemplates: WorkoutSeed[] = [
  {
    "week": 1,
    "dayOffset": 0,
    "workout_type": "休息 + 活动度",
    "title": "周一｜休息 + 活动度（20–30 分钟）",
    "planned_distance_km": 0,
    "planned_duration_min": 25,
    "planned_pace_text": null,
    "planned_pace_seconds_per_km": null,
    "planned_rpe": 1,
    "purpose": "关节唤醒、开始建立恢复节奏",
    "warmup": "无跑步热身；按注意事项做活动度、步行或交叉训练。",
    "main_set": "20–30 分钟；配速/RPE：RPE 1。 注意：髋、踝、足底滚压各 5 分钟",
    "cooldown": "轻柔拉伸 5–10 分钟。",
    "strength_training": false,
    "notes": "来源：专项训练总方案；周目标 24–28 km；原始距离/时间：20–30 分钟；原始强度：RPE 1；力量：否；注意事项：髋、踝、足底滚压各 5 分钟"
  },
  {
    "week": 1,
    "dayOffset": 1,
    "workout_type": "E 轻松跑 + 短加速跑",
    "title": "周二｜E 轻松跑 + 短加速跑（30 分钟 + 4×10 秒）",
    "planned_distance_km": 4.7,
    "planned_duration_min": 30,
    "planned_pace_text": "5'50\"-6'20\"/km",
    "planned_pace_seconds_per_km": 365,
    "planned_rpe": 3,
    "purpose": "复跑、恢复神经节奏",
    "warmup": "慢跑 10–15 分钟 + 动态活动，确认无疼痛后再进入主训练。",
    "main_set": "30 分钟 + 4×10 秒；配速/RPE：5:50–6:20/km；加速跑放松不冲刺。 注意：若小腿紧，改 6×8 秒上坡",
    "cooldown": "慢跑或步行放松 8–10 分钟 + 小腿、髋部轻柔拉伸。",
    "strength_training": true,
    "notes": "来源：专项训练总方案；周目标 24–28 km；原始距离/时间：30 分钟 + 4×10 秒；原始强度：5:50–6:20/km；加速跑放松不冲刺；力量：力量 A 入门 25–30 分钟；注意事项：若小腿紧，改 6×8 秒上坡"
  },
  {
    "week": 1,
    "dayOffset": 2,
    "workout_type": "休息或单车",
    "title": "周三｜休息或单车（30 分钟）",
    "planned_distance_km": 0,
    "planned_duration_min": 30,
    "planned_pace_text": null,
    "planned_pace_seconds_per_km": null,
    "planned_rpe": 2,
    "purpose": "轻度有氧、促进恢复",
    "warmup": "无跑步热身；按注意事项做活动度、步行或交叉训练。",
    "main_set": "30 分钟；配速/RPE：RPE 2–3。 注意：不追求出汗量",
    "cooldown": "轻柔拉伸 5–10 分钟。",
    "strength_training": false,
    "notes": "来源：专项训练总方案；周目标 24–28 km；原始距离/时间：30 分钟；原始强度：RPE 2–3；力量：否；注意事项：不追求出汗量"
  },
  {
    "week": 1,
    "dayOffset": 3,
    "workout_type": "E 轻松跑",
    "title": "周四｜E 轻松跑（35 分钟）",
    "planned_distance_km": 5.5,
    "planned_duration_min": 35,
    "planned_pace_text": "5'50\"-6'20\"/km",
    "planned_pace_seconds_per_km": 365,
    "planned_rpe": 3,
    "purpose": "建立频率",
    "warmup": "动态热身 8–10 分钟，脚踝、髋部和小腿充分活动。",
    "main_set": "35 分钟；配速/RPE：5:50–6:20/km，RPE 3。 注意：结束后做 8 分钟足踝稳定",
    "cooldown": "慢跑或步行放松 8–10 分钟 + 小腿、髋部轻柔拉伸。",
    "strength_training": false,
    "notes": "来源：专项训练总方案；周目标 24–28 km；原始距离/时间：35 分钟；原始强度：5:50–6:20/km，RPE 3；力量：否；注意事项：结束后做 8 分钟足踝稳定"
  },
  {
    "week": 1,
    "dayOffset": 4,
    "workout_type": "E 轻松跑",
    "title": "周五｜E 轻松跑（30 分钟）",
    "planned_distance_km": 4.7,
    "planned_duration_min": 30,
    "planned_pace_text": "5'55\"-6'25\"/km",
    "planned_pace_seconds_per_km": 370,
    "planned_rpe": 3,
    "purpose": "增加组织暴露次数",
    "warmup": "动态热身 8–10 分钟，脚踝、髋部和小腿充分活动。",
    "main_set": "30 分钟；配速/RPE：5:55–6:25/km，RPE 3。 注意：若胫骨发紧，改跑走 4’/1’",
    "cooldown": "慢跑或步行放松 8–10 分钟 + 小腿、髋部轻柔拉伸。",
    "strength_training": false,
    "notes": "来源：专项训练总方案；周目标 24–28 km；原始距离/时间：30 分钟；原始强度：5:55–6:25/km，RPE 3；力量：否；注意事项：若胫骨发紧，改跑走 4’/1’"
  },
  {
    "week": 1,
    "dayOffset": 5,
    "workout_type": "恢复跑",
    "title": "周六｜恢复跑（20 分钟）",
    "planned_distance_km": 3.2,
    "planned_duration_min": 20,
    "planned_pace_text": "6'10\"-6'40\"/km",
    "planned_pace_seconds_per_km": 385,
    "planned_rpe": 2,
    "purpose": "微刺激，不求量",
    "warmup": "动态热身 8–10 分钟，脚踝、髋部和小腿充分活动。",
    "main_set": "20 分钟；配速/RPE：6:10–6:40/km，RPE 2–3。 注意：当天若腿沉，直接只做力量",
    "cooldown": "慢跑或步行放松 8–10 分钟 + 小腿、髋部轻柔拉伸。",
    "strength_training": true,
    "notes": "来源：专项训练总方案；周目标 24–28 km；原始距离/时间：20 分钟；原始强度：6:10–6:40/km，RPE 2–3；力量：力量 B 入门 25–30 分钟；注意事项：当天若腿沉，直接只做力量"
  },
  {
    "week": 1,
    "dayOffset": 6,
    "workout_type": "长距离轻松跑",
    "title": "周日｜长距离轻松跑（50 分钟）",
    "planned_distance_km": 7.9,
    "planned_duration_min": 50,
    "planned_pace_text": "5'55\"-6'25\"/km",
    "planned_pace_seconds_per_km": 370,
    "planned_rpe": 4,
    "purpose": "恢复长跑感觉",
    "warmup": "动态热身 8–10 分钟，脚踝、髋部和小腿充分活动。",
    "main_set": "50 分钟；配速/RPE：5:55–6:25/km，RPE 3–4。 注意：全程克制，最后 10 分钟不能提速",
    "cooldown": "慢跑或步行放松 8–10 分钟 + 小腿、髋部轻柔拉伸。",
    "strength_training": false,
    "notes": "来源：专项训练总方案；周目标 24–28 km；原始距离/时间：50 分钟；原始强度：5:55–6:25/km，RPE 3–4；力量：否；注意事项：全程克制，最后 10 分钟不能提速"
  },
  {
    "week": 2,
    "dayOffset": 7,
    "workout_type": "休息 + 活动度",
    "title": "周一｜休息 + 活动度（20–30 分钟）",
    "planned_distance_km": 0,
    "planned_duration_min": 25,
    "planned_pace_text": null,
    "planned_pace_seconds_per_km": null,
    "planned_rpe": 1,
    "purpose": "恢复",
    "warmup": "无跑步热身；按注意事项做活动度、步行或交叉训练。",
    "main_set": "20–30 分钟；配速/RPE：RPE 1。 注意：重点拉伸髋屈肌、小腿",
    "cooldown": "轻柔拉伸 5–10 分钟。",
    "strength_training": false,
    "notes": "来源：专项训练总方案；周目标 28–32 km；原始距离/时间：20–30 分钟；原始强度：RPE 1；力量：否；注意事项：重点拉伸髋屈肌、小腿"
  },
  {
    "week": 2,
    "dayOffset": 8,
    "workout_type": "E 轻松跑 + 坡冲",
    "title": "周二｜E 轻松跑 + 坡冲（35 分钟 + 4×12 秒）",
    "planned_distance_km": 5.4,
    "planned_duration_min": 35,
    "planned_pace_text": "5'50\"-6'15\"/km",
    "planned_pace_seconds_per_km": 362,
    "planned_rpe": 8,
    "purpose": "继续组织适应、提步频",
    "warmup": "慢跑 10–15 分钟 + 动态活动，确认无疼痛后再进入主训练。",
    "main_set": "35 分钟 + 4×12 秒；配速/RPE：5:50–6:15/km；坡冲 RPE 8 但不过力。 注意：坡冲走回完全恢复",
    "cooldown": "慢跑或步行放松 8–10 分钟 + 小腿、髋部轻柔拉伸。",
    "strength_training": true,
    "notes": "来源：专项训练总方案；周目标 28–32 km；原始距离/时间：35 分钟 + 4×12 秒；原始强度：5:50–6:15/km；坡冲 RPE 8 但不过力；力量：力量 A 30 分钟；注意事项：坡冲走回完全恢复"
  },
  {
    "week": 2,
    "dayOffset": 9,
    "workout_type": "E 轻松跑",
    "title": "周三｜E 轻松跑（30 分钟）",
    "planned_distance_km": 4.6,
    "planned_duration_min": 30,
    "planned_pace_text": "5'55\"-6'20\"/km",
    "planned_pace_seconds_per_km": 368,
    "planned_rpe": 3,
    "purpose": "增加周频率",
    "warmup": "动态热身 8–10 分钟，脚踝、髋部和小腿充分活动。",
    "main_set": "30 分钟；配速/RPE：5:55–6:20/km，RPE 3。 注意：过程能完整说句子",
    "cooldown": "慢跑或步行放松 8–10 分钟 + 小腿、髋部轻柔拉伸。",
    "strength_training": false,
    "notes": "来源：专项训练总方案；周目标 28–32 km；原始距离/时间：30 分钟；原始强度：5:55–6:20/km，RPE 3；力量：否；注意事项：过程能完整说句子"
  },
  {
    "week": 2,
    "dayOffset": 10,
    "workout_type": "E 轻松跑",
    "title": "周四｜E 轻松跑（40 分钟）",
    "planned_distance_km": 6.2,
    "planned_duration_min": 40,
    "planned_pace_text": "5'45\"-6'15\"/km",
    "planned_pace_seconds_per_km": 360,
    "planned_rpe": 4,
    "purpose": "延长单次持续时间",
    "warmup": "动态热身 8–10 分钟，脚踝、髋部和小腿充分活动。",
    "main_set": "40 分钟；配速/RPE：5:45–6:15/km，RPE 3–4。 注意：若广州天气闷热，按 RPE 跑",
    "cooldown": "慢跑或步行放松 8–10 分钟 + 小腿、髋部轻柔拉伸。",
    "strength_training": false,
    "notes": "来源：专项训练总方案；周目标 28–32 km；原始距离/时间：40 分钟；原始强度：5:45–6:15/km，RPE 3–4；力量：否；注意事项：若广州天气闷热，按 RPE 跑"
  },
  {
    "week": 2,
    "dayOffset": 11,
    "workout_type": "休息或单车",
    "title": "周五｜休息或单车（30–35 分钟）",
    "planned_distance_km": 0,
    "planned_duration_min": 32,
    "planned_pace_text": null,
    "planned_pace_seconds_per_km": null,
    "planned_rpe": 2,
    "purpose": "主动恢复",
    "warmup": "无跑步热身；按注意事项做活动度、步行或交叉训练。",
    "main_set": "30–35 分钟；配速/RPE：RPE 2–3。 注意：宁轻勿重",
    "cooldown": "轻柔拉伸 5–10 分钟。",
    "strength_training": false,
    "notes": "来源：专项训练总方案；周目标 28–32 km；原始距离/时间：30–35 分钟；原始强度：RPE 2–3；力量：否；注意事项：宁轻勿重"
  },
  {
    "week": 2,
    "dayOffset": 12,
    "workout_type": "E 轻松跑",
    "title": "周六｜E 轻松跑（30 分钟）",
    "planned_distance_km": 4.6,
    "planned_duration_min": 30,
    "planned_pace_text": "5'55\"-6'25\"/km",
    "planned_pace_seconds_per_km": 370,
    "planned_rpe": 3,
    "purpose": "维持跑频",
    "warmup": "动态热身 8–10 分钟，脚踝、髋部和小腿充分活动。",
    "main_set": "30 分钟；配速/RPE：5:55–6:25/km。 注意：都做完仍应感觉“有余力”",
    "cooldown": "慢跑或步行放松 8–10 分钟 + 小腿、髋部轻柔拉伸。",
    "strength_training": true,
    "notes": "来源：专项训练总方案；周目标 28–32 km；原始距离/时间：30 分钟；原始强度：5:55–6:25/km；力量：力量 B 30 分钟；注意事项：都做完仍应感觉“有余力”"
  },
  {
    "week": 2,
    "dayOffset": 13,
    "workout_type": "长距离轻松跑",
    "title": "周日｜长距离轻松跑（60 分钟）",
    "planned_distance_km": 9.2,
    "planned_duration_min": 60,
    "planned_pace_text": "5'50\"-6'20\"/km",
    "planned_pace_seconds_per_km": 365,
    "planned_rpe": 4,
    "purpose": "拉长有氧时间",
    "warmup": "动态热身 8–10 分钟，脚踝、髋部和小腿充分活动。",
    "main_set": "60 分钟；配速/RPE：5:50–6:20/km，RPE 3–4。 注意：第二天若胫骨/足底晨痛，下一周不加量",
    "cooldown": "慢跑或步行放松 8–10 分钟 + 小腿、髋部轻柔拉伸。",
    "strength_training": false,
    "notes": "来源：专项训练总方案；周目标 28–32 km；原始距离/时间：60 分钟；原始强度：5:50–6:20/km，RPE 3–4；力量：否；注意事项：第二天若胫骨/足底晨痛，下一周不加量"
  },
  {
    "week": 3,
    "dayOffset": 14,
    "workout_type": "休息",
    "title": "周一｜休息",
    "planned_distance_km": 0,
    "planned_duration_min": 0,
    "planned_pace_text": null,
    "planned_pace_seconds_per_km": null,
    "planned_rpe": 1,
    "purpose": "彻底恢复",
    "warmup": "无跑步热身；按注意事项做活动度、步行或交叉训练。",
    "main_set": "休息；配速/RPE：按恢复状态执行。 注意：晚上争取 8.5 小时睡眠",
    "cooldown": "轻柔拉伸 5–10 分钟。",
    "strength_training": false,
    "notes": "来源：专项训练总方案；周目标 34–37 km；原始距离/时间：—；原始强度：—；力量：否；注意事项：晚上争取 8.5 小时睡眠"
  },
  {
    "week": 3,
    "dayOffset": 15,
    "workout_type": "E 轻松跑 + 加速跑",
    "title": "周二｜E 轻松跑 + 加速跑（40 分钟 + 6×10 秒）",
    "planned_distance_km": 6.5,
    "planned_duration_min": 40,
    "planned_pace_text": "5'45\"-6'15\"/km",
    "planned_pace_seconds_per_km": 360,
    "planned_rpe": 3,
    "purpose": "增加基础量",
    "warmup": "慢跑 10–15 分钟 + 动态活动，确认无疼痛后再进入主训练。",
    "main_set": "40 分钟 + 6×10 秒；配速/RPE：5:45–6:15/km。 注意：加速跑只求轻快",
    "cooldown": "慢跑或步行放松 8–10 分钟 + 小腿、髋部轻柔拉伸。",
    "strength_training": true,
    "notes": "来源：专项训练总方案；周目标 34–37 km；原始距离/时间：40 分钟 + 6×10 秒；原始强度：5:45–6:15/km；力量：力量 A 30–35 分钟；注意事项：加速跑只求轻快"
  },
  {
    "week": 3,
    "dayOffset": 16,
    "workout_type": "休息或椭圆机",
    "title": "周三｜休息或椭圆机（30 分钟）",
    "planned_distance_km": 0,
    "planned_duration_min": 30,
    "planned_pace_text": null,
    "planned_pace_seconds_per_km": null,
    "planned_rpe": 2,
    "purpose": "减冲击恢复",
    "warmup": "无跑步热身；按注意事项做活动度、步行或交叉训练。",
    "main_set": "30 分钟；配速/RPE：RPE 2–3。 注意：若感觉很新鲜可改 25 分钟恢复跑",
    "cooldown": "轻柔拉伸 5–10 分钟。",
    "strength_training": false,
    "notes": "来源：专项训练总方案；周目标 34–37 km；原始距离/时间：30 分钟；原始强度：RPE 2–3；力量：否；注意事项：若感觉很新鲜可改 25 分钟恢复跑"
  },
  {
    "week": 3,
    "dayOffset": 17,
    "workout_type": "轻松跑上量",
    "title": "周四｜轻松跑上量（45 分钟）",
    "planned_distance_km": 7.3,
    "planned_duration_min": 45,
    "planned_pace_text": "5'45\"-6'15\"/km",
    "planned_pace_seconds_per_km": 360,
    "planned_rpe": 3,
    "purpose": "开始接触“上端轻松跑”",
    "warmup": "动态热身 8–10 分钟，脚踝、髋部和小腿充分活动。",
    "main_set": "45 分钟；配速/RPE：5:45–6:15/km，最后 10 分钟 5:30–5:40。 注意：不允许变成稳态跑",
    "cooldown": "慢跑或步行放松 8–10 分钟 + 小腿、髋部轻柔拉伸。",
    "strength_training": false,
    "notes": "来源：专项训练总方案；周目标 34–37 km；原始距离/时间：45 分钟；原始强度：5:45–6:15/km，最后 10 分钟 5:30–5:40；力量：否；注意事项：不允许变成稳态跑"
  },
  {
    "week": 3,
    "dayOffset": 18,
    "workout_type": "恢复跑",
    "title": "周五｜恢复跑（30 分钟）",
    "planned_distance_km": 4.8,
    "planned_duration_min": 30,
    "planned_pace_text": "6'05\"-6'35\"/km",
    "planned_pace_seconds_per_km": 380,
    "planned_rpe": 2,
    "purpose": "促进恢复",
    "warmup": "动态热身 8–10 分钟，脚踝、髋部和小腿充分活动。",
    "main_set": "30 分钟；配速/RPE：6:05–6:35/km，RPE 2–3。 注意：脚落地轻，步幅短",
    "cooldown": "慢跑或步行放松 8–10 分钟 + 小腿、髋部轻柔拉伸。",
    "strength_training": false,
    "notes": "来源：专项训练总方案；周目标 34–37 km；原始距离/时间：30 分钟；原始强度：6:05–6:35/km，RPE 2–3；力量：否；注意事项：脚落地轻，步幅短"
  },
  {
    "week": 3,
    "dayOffset": 19,
    "workout_type": "E 轻松跑",
    "title": "周六｜E 轻松跑（35 分钟）",
    "planned_distance_km": 5.6,
    "planned_duration_min": 35,
    "planned_pace_text": "5'50\"-6'20\"/km",
    "planned_pace_seconds_per_km": 365,
    "planned_rpe": 3,
    "purpose": "堆叠频率",
    "warmup": "动态热身 8–10 分钟，脚踝、髋部和小腿充分活动。",
    "main_set": "35 分钟；配速/RPE：5:50–6:20/km。 注意：力量后若明显疲劳，删掉次日提速念头",
    "cooldown": "慢跑或步行放松 8–10 分钟 + 小腿、髋部轻柔拉伸。",
    "strength_training": true,
    "notes": "来源：专项训练总方案；周目标 34–37 km；原始距离/时间：35 分钟；原始强度：5:50–6:20/km；力量：力量 B 30 分钟；注意事项：力量后若明显疲劳，删掉次日提速念头"
  },
  {
    "week": 3,
    "dayOffset": 20,
    "workout_type": "长距离轻松跑",
    "title": "周日｜长距离轻松跑（70 分钟）",
    "planned_distance_km": 11.3,
    "planned_duration_min": 70,
    "planned_pace_text": "5'50\"-6'20\"/km",
    "planned_pace_seconds_per_km": 365,
    "planned_rpe": 4,
    "purpose": "长跑进阶",
    "warmup": "动态热身 8–10 分钟，脚踝、髋部和小腿充分活动。",
    "main_set": "70 分钟；配速/RPE：5:50–6:20/km，RPE 3–4。 注意：结束后 30 分钟内补碳水+蛋白",
    "cooldown": "慢跑或步行放松 8–10 分钟 + 小腿、髋部轻柔拉伸。",
    "strength_training": false,
    "notes": "来源：专项训练总方案；周目标 34–37 km；原始距离/时间：70 分钟；原始强度：5:50–6:20/km，RPE 3–4；力量：否；注意事项：结束后 30 分钟内补碳水+蛋白"
  },
  {
    "week": 4,
    "dayOffset": 21,
    "workout_type": "休息",
    "title": "周一｜休息",
    "planned_distance_km": 0,
    "planned_duration_min": 0,
    "planned_pace_text": null,
    "planned_pace_seconds_per_km": null,
    "planned_rpe": 1,
    "purpose": "减量周恢复",
    "warmup": "无跑步热身；按注意事项做活动度、步行或交叉训练。",
    "main_set": "休息；配速/RPE：按恢复状态执行。 注意：记录体重、睡眠、主观疲劳",
    "cooldown": "轻柔拉伸 5–10 分钟。",
    "strength_training": false,
    "notes": "来源：专项训练总方案；周目标 28–31 km；原始距离/时间：—；原始强度：—；力量：否；注意事项：记录体重、睡眠、主观疲劳"
  },
  {
    "week": 4,
    "dayOffset": 22,
    "workout_type": "E 轻松跑",
    "title": "周二｜E 轻松跑（35 分钟）",
    "planned_distance_km": 4.8,
    "planned_duration_min": 35,
    "planned_pace_text": "5'50\"-6'20\"/km",
    "planned_pace_seconds_per_km": 365,
    "planned_rpe": 3,
    "purpose": "维持频率",
    "warmup": "动态热身 8–10 分钟，脚踝、髋部和小腿充分活动。",
    "main_set": "35 分钟；配速/RPE：5:50–6:20/km。 注意：力量本周减一组",
    "cooldown": "慢跑或步行放松 8–10 分钟 + 小腿、髋部轻柔拉伸。",
    "strength_training": true,
    "notes": "来源：专项训练总方案；周目标 28–31 km；原始距离/时间：35 分钟；原始强度：5:50–6:20/km；力量：力量 A 25–30 分钟；注意事项：力量本周减一组"
  },
  {
    "week": 4,
    "dayOffset": 23,
    "workout_type": "E 轻松跑",
    "title": "周三｜E 轻松跑（30 分钟）",
    "planned_distance_km": 4.1,
    "planned_duration_min": 30,
    "planned_pace_text": "5'55\"-6'25\"/km",
    "planned_pace_seconds_per_km": 370,
    "planned_rpe": 3,
    "purpose": "保持跑感",
    "warmup": "动态热身 8–10 分钟，脚踝、髋部和小腿充分活动。",
    "main_set": "30 分钟；配速/RPE：5:55–6:25/km。 注意：全程鼻呼吸可控",
    "cooldown": "慢跑或步行放松 8–10 分钟 + 小腿、髋部轻柔拉伸。",
    "strength_training": false,
    "notes": "来源：专项训练总方案；周目标 28–31 km；原始距离/时间：30 分钟；原始强度：5:55–6:25/km；力量：否；注意事项：全程鼻呼吸可控"
  },
  {
    "week": 4,
    "dayOffset": 24,
    "workout_type": "稳态基准跑",
    "title": "周四｜稳态基准跑（15 分钟 easy + 20 分钟稳态 + 10 分钟放松）",
    "planned_distance_km": 6.2,
    "planned_duration_min": 45,
    "planned_pace_text": "5'20\"-5'30\"/km",
    "planned_pace_seconds_per_km": 325,
    "planned_rpe": 5,
    "purpose": "检查有氧与动作稳定性",
    "warmup": "动态热身 8–10 分钟，脚踝、髋部和小腿充分活动。",
    "main_set": "15 分钟 easy + 20 分钟稳态 + 10 分钟放松；配速/RPE：稳态段 5:20–5:30/km，RPE 5。 注意：这是基准，不是 TT",
    "cooldown": "慢跑或步行放松 8–10 分钟 + 小腿、髋部轻柔拉伸。",
    "strength_training": false,
    "notes": "来源：专项训练总方案；周目标 28–31 km；原始距离/时间：15 分钟 easy + 20 分钟稳态 + 10 分钟放松；原始强度：稳态段 5:20–5:30/km，RPE 5；力量：否；注意事项：这是基准，不是 TT"
  },
  {
    "week": 4,
    "dayOffset": 25,
    "workout_type": "休息",
    "title": "周五｜休息",
    "planned_distance_km": 0,
    "planned_duration_min": 0,
    "planned_pace_text": null,
    "planned_pace_seconds_per_km": null,
    "planned_rpe": 1,
    "purpose": "吸收训练",
    "warmup": "无跑步热身；按注意事项做活动度、步行或交叉训练。",
    "main_set": "休息；配速/RPE：按恢复状态执行。 注意：若想动，步行 30 分钟即可",
    "cooldown": "轻柔拉伸 5–10 分钟。",
    "strength_training": false,
    "notes": "来源：专项训练总方案；周目标 28–31 km；原始距离/时间：—；原始强度：—；力量：否；注意事项：若想动，步行 30 分钟即可"
  },
  {
    "week": 4,
    "dayOffset": 26,
    "workout_type": "恢复跑",
    "title": "周六｜恢复跑（30 分钟）",
    "planned_distance_km": 4.1,
    "planned_duration_min": 30,
    "planned_pace_text": "6'05\"-6'35\"/km",
    "planned_pace_seconds_per_km": 380,
    "planned_rpe": 3,
    "purpose": "轻微唤醒",
    "warmup": "动态热身 8–10 分钟，脚踝、髋部和小腿充分活动。",
    "main_set": "30 分钟；配速/RPE：6:05–6:35/km。 注意：只做轻版本",
    "cooldown": "慢跑或步行放松 8–10 分钟 + 小腿、髋部轻柔拉伸。",
    "strength_training": true,
    "notes": "来源：专项训练总方案；周目标 28–31 km；原始距离/时间：30 分钟；原始强度：6:05–6:35/km；力量：力量 B 20–25 分钟；注意事项：只做轻版本"
  },
  {
    "week": 4,
    "dayOffset": 27,
    "workout_type": "长距离轻松跑",
    "title": "周日｜长距离轻松跑（75 分钟）",
    "planned_distance_km": 10.3,
    "planned_duration_min": 75,
    "planned_pace_text": "5'50\"-6'20\"/km",
    "planned_pace_seconds_per_km": 365,
    "planned_rpe": 3,
    "purpose": "四周检查点",
    "warmup": "动态热身 8–10 分钟，脚踝、髋部和小腿充分活动。",
    "main_set": "75 分钟；配速/RPE：5:50–6:20/km。 注意：若长跑后第二天异常酸痛，下阶段不加天数",
    "cooldown": "慢跑或步行放松 8–10 分钟 + 小腿、髋部轻柔拉伸。",
    "strength_training": false,
    "notes": "来源：专项训练总方案；周目标 28–31 km；原始距离/时间：75 分钟；原始强度：5:50–6:20/km；力量：否；注意事项：若长跑后第二天异常酸痛，下阶段不加天数"
  },
  {
    "week": 5,
    "dayOffset": 28,
    "workout_type": "休息",
    "title": "周一｜休息",
    "planned_distance_km": 0,
    "planned_duration_min": 0,
    "planned_pace_text": null,
    "planned_pace_seconds_per_km": null,
    "planned_rpe": 1,
    "purpose": "恢复",
    "warmup": "无跑步热身；按注意事项做活动度、步行或交叉训练。",
    "main_set": "休息；配速/RPE：按恢复状态执行。 注意：补足睡眠",
    "cooldown": "轻柔拉伸 5–10 分钟。",
    "strength_training": false,
    "notes": "来源：专项训练总方案；周目标 40–44 km；原始距离/时间：—；原始强度：—；力量：否；注意事项：补足睡眠"
  },
  {
    "week": 5,
    "dayOffset": 29,
    "workout_type": "E 轻松跑",
    "title": "周二｜E 轻松跑（40 分钟）",
    "planned_distance_km": 7.8,
    "planned_duration_min": 40,
    "planned_pace_text": "5'45\"-6'15\"/km",
    "planned_pace_seconds_per_km": 360,
    "planned_rpe": 3,
    "purpose": "周量上台阶",
    "warmup": "动态热身 8–10 分钟，脚踝、髋部和小腿充分活动。",
    "main_set": "40 分钟；配速/RPE：5:45–6:15/km。 注意：力量开始进入正常量",
    "cooldown": "慢跑或步行放松 8–10 分钟 + 小腿、髋部轻柔拉伸。",
    "strength_training": true,
    "notes": "来源：专项训练总方案；周目标 40–44 km；原始距离/时间：40 分钟；原始强度：5:45–6:15/km；力量：力量 A 35–40 分钟；注意事项：力量开始进入正常量"
  },
  {
    "week": 5,
    "dayOffset": 30,
    "workout_type": "恢复跑",
    "title": "周三｜恢复跑（35 分钟）",
    "planned_distance_km": 6.8,
    "planned_duration_min": 35,
    "planned_pace_text": "6'00\"-6'30\"/km",
    "planned_pace_seconds_per_km": 375,
    "planned_rpe": 3,
    "purpose": "恢复性堆量",
    "warmup": "动态热身 8–10 分钟，脚踝、髋部和小腿充分活动。",
    "main_set": "35 分钟；配速/RPE：6:00–6:30/km。 注意：感觉重就慢",
    "cooldown": "慢跑或步行放松 8–10 分钟 + 小腿、髋部轻柔拉伸。",
    "strength_training": false,
    "notes": "来源：专项训练总方案；周目标 40–44 km；原始距离/时间：35 分钟；原始强度：6:00–6:30/km；力量：否；注意事项：感觉重就慢"
  },
  {
    "week": 5,
    "dayOffset": 31,
    "workout_type": "稳定有氧块",
    "title": "周四｜稳定有氧块（15 分钟 easy + 2×10 分钟稳态 + 10 分钟放松）",
    "planned_distance_km": 0,
    "planned_duration_min": 45,
    "planned_pace_text": "5'15\"-5'25\"/km",
    "planned_pace_seconds_per_km": 320,
    "planned_rpe": 1,
    "purpose": "引入真正稳态训练",
    "warmup": "无跑步热身；按注意事项做活动度、步行或交叉训练。",
    "main_set": "15 分钟 easy + 2×10 分钟稳态 + 10 分钟放松；配速/RPE：稳态 5:15–5:25/km，间歇慢跑 3 分钟。 注意：结束后应感觉“还能再做一点”",
    "cooldown": "轻柔拉伸 5–10 分钟。",
    "strength_training": false,
    "notes": "来源：专项训练总方案；周目标 40–44 km；原始距离/时间：15 分钟 easy + 2×10 分钟稳态 + 10 分钟放松；原始强度：稳态 5:15–5:25/km，间歇慢跑 3 分钟；力量：否；注意事项：结束后应感觉“还能再做一点”"
  },
  {
    "week": 5,
    "dayOffset": 32,
    "workout_type": "E 轻松跑",
    "title": "周五｜E 轻松跑（30 分钟）",
    "planned_distance_km": 5.9,
    "planned_duration_min": 30,
    "planned_pace_text": "5'50\"-6'20\"/km",
    "planned_pace_seconds_per_km": 365,
    "planned_rpe": 3,
    "purpose": "维持频率",
    "warmup": "动态热身 8–10 分钟，脚踝、髋部和小腿充分活动。",
    "main_set": "30 分钟；配速/RPE：5:50–6:20/km。 注意：不做任何快跑",
    "cooldown": "慢跑或步行放松 8–10 分钟 + 小腿、髋部轻柔拉伸。",
    "strength_training": false,
    "notes": "来源：专项训练总方案；周目标 40–44 km；原始距离/时间：30 分钟；原始强度：5:50–6:20/km；力量：否；注意事项：不做任何快跑"
  },
  {
    "week": 5,
    "dayOffset": 33,
    "workout_type": "E 轻松跑",
    "title": "周六｜E 轻松跑（35 分钟）",
    "planned_distance_km": 6.8,
    "planned_duration_min": 35,
    "planned_pace_text": "5'45\"-6'15\"/km",
    "planned_pace_seconds_per_km": 360,
    "planned_rpe": 3,
    "purpose": "为长跑做铺垫",
    "warmup": "动态热身 8–10 分钟，脚踝、髋部和小腿充分活动。",
    "main_set": "35 分钟；配速/RPE：5:45–6:15/km。 注意：若 DOMS 明显，减少单腿动作",
    "cooldown": "慢跑或步行放松 8–10 分钟 + 小腿、髋部轻柔拉伸。",
    "strength_training": true,
    "notes": "来源：专项训练总方案；周目标 40–44 km；原始距离/时间：35 分钟；原始强度：5:45–6:15/km；力量：力量 B 30–35 分钟；注意事项：若 DOMS 明显，减少单腿动作"
  },
  {
    "week": 5,
    "dayOffset": 34,
    "workout_type": "长距离轻松跑",
    "title": "周日｜长距离轻松跑（75 分钟）",
    "planned_distance_km": 14.7,
    "planned_duration_min": 75,
    "planned_pace_text": "5'45\"-6'15\"/km",
    "planned_pace_seconds_per_km": 360,
    "planned_rpe": 3,
    "purpose": "有氧重建",
    "warmup": "动态热身 8–10 分钟，脚踝、髋部和小腿充分活动。",
    "main_set": "75 分钟；配速/RPE：5:45–6:15/km。 注意：训练后补 30–60 g 碳水",
    "cooldown": "慢跑或步行放松 8–10 分钟 + 小腿、髋部轻柔拉伸。",
    "strength_training": false,
    "notes": "来源：专项训练总方案；周目标 40–44 km；原始距离/时间：75 分钟；原始强度：5:45–6:15/km；力量：否；注意事项：训练后补 30–60 g 碳水"
  },
  {
    "week": 6,
    "dayOffset": 35,
    "workout_type": "休息",
    "title": "周一｜休息",
    "planned_distance_km": 0,
    "planned_duration_min": 0,
    "planned_pace_text": null,
    "planned_pace_seconds_per_km": null,
    "planned_rpe": 1,
    "purpose": "恢复",
    "warmup": "无跑步热身；按注意事项做活动度、步行或交叉训练。",
    "main_set": "休息；配速/RPE：按恢复状态执行。 注意：体重若下降过快，增加主食",
    "cooldown": "轻柔拉伸 5–10 分钟。",
    "strength_training": false,
    "notes": "来源：专项训练总方案；周目标 46–50 km；原始距离/时间：—；原始强度：—；力量：否；注意事项：体重若下降过快，增加主食"
  },
  {
    "week": 6,
    "dayOffset": 36,
    "workout_type": "E 轻松跑 + 加速跑",
    "title": "周二｜E 轻松跑 + 加速跑（45 分钟 + 6×100 米）",
    "planned_distance_km": 8.6,
    "planned_duration_min": 45,
    "planned_pace_text": "5'45\"-6'10\"/km",
    "planned_pace_seconds_per_km": 358,
    "planned_rpe": 3,
    "purpose": "提高跑感",
    "warmup": "慢跑 10–15 分钟 + 动态活动，确认无疼痛后再进入主训练。",
    "main_set": "45 分钟 + 6×100 米；配速/RPE：5:45–6:10/km；加速跑放松。 注意：100 米不是冲刺",
    "cooldown": "慢跑或步行放松 8–10 分钟 + 小腿、髋部轻柔拉伸。",
    "strength_training": true,
    "notes": "来源：专项训练总方案；周目标 46–50 km；原始距离/时间：45 分钟 + 6×100 米；原始强度：5:45–6:10/km；加速跑放松；力量：力量 A 35–40 分钟；注意事项：100 米不是冲刺"
  },
  {
    "week": 6,
    "dayOffset": 37,
    "workout_type": "恢复跑",
    "title": "周三｜恢复跑（40 分钟）",
    "planned_distance_km": 7.7,
    "planned_duration_min": 40,
    "planned_pace_text": "6'00\"-6'30\"/km",
    "planned_pace_seconds_per_km": 375,
    "planned_rpe": 3,
    "purpose": "主动恢复",
    "warmup": "动态热身 8–10 分钟，脚踝、髋部和小腿充分活动。",
    "main_set": "40 分钟；配速/RPE：6:00–6:30/km。 注意：热湿环境按 RPE 执行",
    "cooldown": "慢跑或步行放松 8–10 分钟 + 小腿、髋部轻柔拉伸。",
    "strength_training": false,
    "notes": "来源：专项训练总方案；周目标 46–50 km；原始距离/时间：40 分钟；原始强度：6:00–6:30/km；力量：否；注意事项：热湿环境按 RPE 执行"
  },
  {
    "week": 6,
    "dayOffset": 38,
    "workout_type": "稳定有氧块",
    "title": "周四｜稳定有氧块（15 分钟 easy + 3×10 分钟稳态 + 放松）",
    "planned_distance_km": 0,
    "planned_duration_min": 45,
    "planned_pace_text": "5'10\"-5'20\"/km",
    "planned_pace_seconds_per_km": 315,
    "planned_rpe": 1,
    "purpose": "提高持续有氧质量",
    "warmup": "无跑步热身；按注意事项做活动度、步行或交叉训练。",
    "main_set": "15 分钟 easy + 3×10 分钟稳态 + 放松；配速/RPE：稳态 5:10–5:20/km，间歇 2 分钟。 注意：最后一组动作不能散",
    "cooldown": "轻柔拉伸 5–10 分钟。",
    "strength_training": false,
    "notes": "来源：专项训练总方案；周目标 46–50 km；原始距离/时间：15 分钟 easy + 3×10 分钟稳态 + 放松；原始强度：稳态 5:10–5:20/km，间歇 2 分钟；力量：否；注意事项：最后一组动作不能散"
  },
  {
    "week": 6,
    "dayOffset": 39,
    "workout_type": "E 轻松跑",
    "title": "周五｜E 轻松跑（35 分钟）",
    "planned_distance_km": 6.7,
    "planned_duration_min": 35,
    "planned_pace_text": "5'50\"-6'20\"/km",
    "planned_pace_seconds_per_km": 365,
    "planned_rpe": 3,
    "purpose": "吸收训练",
    "warmup": "动态热身 8–10 分钟，脚踝、髋部和小腿充分活动。",
    "main_set": "35 分钟；配速/RPE：5:50–6:20/km。 注意：若腿沉，可减到 30 分钟",
    "cooldown": "慢跑或步行放松 8–10 分钟 + 小腿、髋部轻柔拉伸。",
    "strength_training": false,
    "notes": "来源：专项训练总方案；周目标 46–50 km；原始距离/时间：35 分钟；原始强度：5:50–6:20/km；力量：否；注意事项：若腿沉，可减到 30 分钟"
  },
  {
    "week": 6,
    "dayOffset": 40,
    "workout_type": "E 轻松跑",
    "title": "周六｜E 轻松跑（40 分钟）",
    "planned_distance_km": 7.7,
    "planned_duration_min": 40,
    "planned_pace_text": "5'45\"-6'15\"/km",
    "planned_pace_seconds_per_km": 360,
    "planned_rpe": 3,
    "purpose": "周量堆叠",
    "warmup": "动态热身 8–10 分钟，脚踝、髋部和小腿充分活动。",
    "main_set": "40 分钟；配速/RPE：5:45–6:15/km。 注意：保留余力给周日长跑",
    "cooldown": "慢跑或步行放松 8–10 分钟 + 小腿、髋部轻柔拉伸。",
    "strength_training": true,
    "notes": "来源：专项训练总方案；周目标 46–50 km；原始距离/时间：40 分钟；原始强度：5:45–6:15/km；力量：力量 B 30 分钟；注意事项：保留余力给周日长跑"
  },
  {
    "week": 6,
    "dayOffset": 41,
    "workout_type": "长距离跑",
    "title": "周日｜长距离跑（90 分钟）",
    "planned_distance_km": 17.3,
    "planned_duration_min": 90,
    "planned_pace_text": null,
    "planned_pace_seconds_per_km": null,
    "planned_rpe": 3,
    "purpose": "开始练长跑后程控制",
    "warmup": "动态热身 8–10 分钟，脚踝、髋部和小腿充分活动。",
    "main_set": "90 分钟；配速/RPE：前 70 分钟 5:50–6:15，后 20 分钟 5:20–5:30。 注意：不是比赛配速，控制欲望",
    "cooldown": "慢跑或步行放松 8–10 分钟 + 小腿、髋部轻柔拉伸。",
    "strength_training": false,
    "notes": "来源：专项训练总方案；周目标 46–50 km；原始距离/时间：90 分钟；原始强度：前 70 分钟 5:50–6:15，后 20 分钟 5:20–5:30；力量：否；注意事项：不是比赛配速，控制欲望"
  },
  {
    "week": 7,
    "dayOffset": 42,
    "workout_type": "休息",
    "title": "周一｜休息",
    "planned_distance_km": 0,
    "planned_duration_min": 0,
    "planned_pace_text": null,
    "planned_pace_seconds_per_km": null,
    "planned_rpe": 1,
    "purpose": "恢复",
    "warmup": "无跑步热身；按注意事项做活动度、步行或交叉训练。",
    "main_set": "休息；配速/RPE：按恢复状态执行。 注意：睡眠少于 7.5 小时则绝不加课",
    "cooldown": "轻柔拉伸 5–10 分钟。",
    "strength_training": false,
    "notes": "来源：专项训练总方案；周目标 50–54 km；原始距离/时间：—；原始强度：—；力量：否；注意事项：睡眠少于 7.5 小时则绝不加课"
  },
  {
    "week": 7,
    "dayOffset": 43,
    "workout_type": "阈值启蒙",
    "title": "周二｜阈值启蒙（15 分钟热身 + 4×5 分钟 T-light + 10 分钟放松）",
    "planned_distance_km": 7.5,
    "planned_duration_min": 45,
    "planned_pace_text": "4'55\"-5'00\"/km",
    "planned_pace_seconds_per_km": 298,
    "planned_rpe": 6,
    "purpose": "第一次系统接触阈值",
    "warmup": "慢跑 10–15 分钟 + 动态活动，确认无疼痛后再进入主训练。",
    "main_set": "15 分钟热身 + 4×5 分钟 T-light + 10 分钟放松；配速/RPE：T-light 4:55–5:00/km，组间 2 分钟慢跑，RPE 6–7。 注意：若 2 组后呼吸失控，立刻改稳态",
    "cooldown": "慢跑或步行放松 8–10 分钟 + 小腿、髋部轻柔拉伸。",
    "strength_training": false,
    "notes": "来源：专项训练总方案；周目标 50–54 km；原始距离/时间：15 分钟热身 + 4×5 分钟 T-light + 10 分钟放松；原始强度：T-light 4:55–5:00/km，组间 2 分钟慢跑，RPE 6–7；力量：否；注意事项：若 2 组后呼吸失控，立刻改稳态"
  },
  {
    "week": 7,
    "dayOffset": 44,
    "workout_type": "恢复跑",
    "title": "周三｜恢复跑（40 分钟）",
    "planned_distance_km": 6.7,
    "planned_duration_min": 40,
    "planned_pace_text": "6'00\"-6'30\"/km",
    "planned_pace_seconds_per_km": 375,
    "planned_rpe": 3,
    "purpose": "恢复",
    "warmup": "动态热身 8–10 分钟，脚踝、髋部和小腿充分活动。",
    "main_set": "40 分钟；配速/RPE：6:00–6:30/km。 注意：真恢复，不要越跑越快",
    "cooldown": "慢跑或步行放松 8–10 分钟 + 小腿、髋部轻柔拉伸。",
    "strength_training": false,
    "notes": "来源：专项训练总方案；周目标 50–54 km；原始距离/时间：40 分钟；原始强度：6:00–6:30/km；力量：否；注意事项：真恢复，不要越跑越快"
  },
  {
    "week": 7,
    "dayOffset": 45,
    "workout_type": "E 轻松跑",
    "title": "周四｜E 轻松跑（50 分钟）",
    "planned_distance_km": 8.4,
    "planned_duration_min": 50,
    "planned_pace_text": "5'45\"-6'15\"/km",
    "planned_pace_seconds_per_km": 360,
    "planned_rpe": 3,
    "purpose": "用低强度吸收阈值刺激",
    "warmup": "动态热身 8–10 分钟，脚踝、髋部和小腿充分活动。",
    "main_set": "50 分钟；配速/RPE：5:45–6:15/km。 注意：力量不过度追重量",
    "cooldown": "慢跑或步行放松 8–10 分钟 + 小腿、髋部轻柔拉伸。",
    "strength_training": true,
    "notes": "来源：专项训练总方案；周目标 50–54 km；原始距离/时间：50 分钟；原始强度：5:45–6:15/km；力量：力量 A 35–40 分钟；注意事项：力量不过度追重量"
  },
  {
    "week": 7,
    "dayOffset": 46,
    "workout_type": "E 轻松跑 + 坡冲",
    "title": "周五｜E 轻松跑 + 坡冲（45 分钟 + 6×10 秒）",
    "planned_distance_km": 7.5,
    "planned_duration_min": 45,
    "planned_pace_text": "5'45\"-6'15\"/km",
    "planned_pace_seconds_per_km": 360,
    "planned_rpe": 3,
    "purpose": "维持神经速度",
    "warmup": "慢跑 10–15 分钟 + 动态活动，确认无疼痛后再进入主训练。",
    "main_set": "45 分钟 + 6×10 秒；配速/RPE：5:45–6:15/km。 注意：坡冲后完全走回恢复",
    "cooldown": "慢跑或步行放松 8–10 分钟 + 小腿、髋部轻柔拉伸。",
    "strength_training": false,
    "notes": "来源：专项训练总方案；周目标 50–54 km；原始距离/时间：45 分钟 + 6×10 秒；原始强度：5:45–6:15/km；力量：否；注意事项：坡冲后完全走回恢复"
  },
  {
    "week": 7,
    "dayOffset": 47,
    "workout_type": "恢复跑",
    "title": "周六｜恢复跑（35 分钟）",
    "planned_distance_km": 5.9,
    "planned_duration_min": 35,
    "planned_pace_text": "6'05\"-6'35\"/km",
    "planned_pace_seconds_per_km": 380,
    "planned_rpe": 3,
    "purpose": "周内减冲击",
    "warmup": "动态热身 8–10 分钟，脚踝、髋部和小腿充分活动。",
    "main_set": "35 分钟；配速/RPE：6:05–6:35/km。 注意：如果小腿硬，力量缩量",
    "cooldown": "慢跑或步行放松 8–10 分钟 + 小腿、髋部轻柔拉伸。",
    "strength_training": true,
    "notes": "来源：专项训练总方案；周目标 50–54 km；原始距离/时间：35 分钟；原始强度：6:05–6:35/km；力量：力量 B 25–30 分钟；注意事项：如果小腿硬，力量缩量"
  },
  {
    "week": 7,
    "dayOffset": 48,
    "workout_type": "长距离跑",
    "title": "周日｜长距离跑（95 分钟）",
    "planned_distance_km": 15.9,
    "planned_duration_min": 95,
    "planned_pace_text": "5'45\"-6'15\"/km",
    "planned_pace_seconds_per_km": 360,
    "planned_rpe": 3,
    "purpose": "建立“长而稳”的长跑",
    "warmup": "动态热身 8–10 分钟，脚踝、髋部和小腿充分活动。",
    "main_set": "95 分钟；配速/RPE：5:45–6:15/km，最后 15 分钟可到 5:20–5:30。 注意：次日若疲劳过大，下周不升量",
    "cooldown": "慢跑或步行放松 8–10 分钟 + 小腿、髋部轻柔拉伸。",
    "strength_training": false,
    "notes": "来源：专项训练总方案；周目标 50–54 km；原始距离/时间：95 分钟；原始强度：5:45–6:15/km，最后 15 分钟可到 5:20–5:30；力量：否；注意事项：次日若疲劳过大，下周不升量"
  },
  {
    "week": 8,
    "dayOffset": 49,
    "workout_type": "休息",
    "title": "周一｜休息",
    "planned_distance_km": 0,
    "planned_duration_min": 0,
    "planned_pace_text": null,
    "planned_pace_seconds_per_km": null,
    "planned_rpe": 1,
    "purpose": "减量周恢复",
    "warmup": "无跑步热身；按注意事项做活动度、步行或交叉训练。",
    "main_set": "休息；配速/RPE：按恢复状态执行。 注意：维持作息",
    "cooldown": "轻柔拉伸 5–10 分钟。",
    "strength_training": false,
    "notes": "来源：专项训练总方案；周目标 42–46 km；原始距离/时间：—；原始强度：—；力量：否；注意事项：维持作息"
  },
  {
    "week": 8,
    "dayOffset": 50,
    "workout_type": "连续阈值轻量",
    "title": "周二｜连续阈值轻量（15 分钟 easy + 20 分钟连续稳阈 + 10 分钟放松）",
    "planned_distance_km": 8.6,
    "planned_duration_min": 45,
    "planned_pace_text": "4'58\"-5'03\"/km",
    "planned_pace_seconds_per_km": 300,
    "planned_rpe": 6,
    "purpose": "观察阈值连续能力",
    "warmup": "慢跑 10–15 分钟 + 动态活动，确认无疼痛后再进入主训练。",
    "main_set": "15 分钟 easy + 20 分钟连续稳阈 + 10 分钟放松；配速/RPE：4:58–5:03/km，RPE 6–7。 注意：仍应保技术动作",
    "cooldown": "慢跑或步行放松 8–10 分钟 + 小腿、髋部轻柔拉伸。",
    "strength_training": false,
    "notes": "来源：专项训练总方案；周目标 42–46 km；原始距离/时间：15 分钟 easy + 20 分钟连续稳阈 + 10 分钟放松；原始强度：4:58–5:03/km，RPE 6–7；力量：否；注意事项：仍应保技术动作"
  },
  {
    "week": 8,
    "dayOffset": 51,
    "workout_type": "恢复跑",
    "title": "周三｜恢复跑（35 分钟）",
    "planned_distance_km": 6.7,
    "planned_duration_min": 35,
    "planned_pace_text": "6'00\"-6'30\"/km",
    "planned_pace_seconds_per_km": 375,
    "planned_rpe": 3,
    "purpose": "恢复",
    "warmup": "动态热身 8–10 分钟，脚踝、髋部和小腿充分活动。",
    "main_set": "35 分钟；配速/RPE：6:00–6:30/km。 注意：不做加速",
    "cooldown": "慢跑或步行放松 8–10 分钟 + 小腿、髋部轻柔拉伸。",
    "strength_training": false,
    "notes": "来源：专项训练总方案；周目标 42–46 km；原始距离/时间：35 分钟；原始强度：6:00–6:30/km；力量：否；注意事项：不做加速"
  },
  {
    "week": 8,
    "dayOffset": 52,
    "workout_type": "E 轻松跑",
    "title": "周四｜E 轻松跑（45 分钟）",
    "planned_distance_km": 8.6,
    "planned_duration_min": 45,
    "planned_pace_text": "5'45\"-6'15\"/km",
    "planned_pace_seconds_per_km": 360,
    "planned_rpe": 3,
    "purpose": "保持频率",
    "warmup": "动态热身 8–10 分钟，脚踝、髋部和小腿充分活动。",
    "main_set": "45 分钟；配速/RPE：5:45–6:15/km。 注意：本周力量减量",
    "cooldown": "慢跑或步行放松 8–10 分钟 + 小腿、髋部轻柔拉伸。",
    "strength_training": true,
    "notes": "来源：专项训练总方案；周目标 42–46 km；原始距离/时间：45 分钟；原始强度：5:45–6:15/km；力量：力量 A 25–30 分钟；注意事项：本周力量减量"
  },
  {
    "week": 8,
    "dayOffset": 53,
    "workout_type": "休息",
    "title": "周五｜休息",
    "planned_distance_km": 0,
    "planned_duration_min": 0,
    "planned_pace_text": null,
    "planned_pace_seconds_per_km": null,
    "planned_rpe": 1,
    "purpose": "为测试蓄一点劲",
    "warmup": "无跑步热身；按注意事项做活动度、步行或交叉训练。",
    "main_set": "休息；配速/RPE：按恢复状态执行。 注意：补水、不要熬夜",
    "cooldown": "轻柔拉伸 5–10 分钟。",
    "strength_training": false,
    "notes": "来源：专项训练总方案；周目标 42–46 km；原始距离/时间：—；原始强度：—；力量：否；注意事项：补水、不要熬夜"
  },
  {
    "week": 8,
    "dayOffset": 54,
    "workout_type": "受控五公里测试",
    "title": "周六｜受控五公里测试（热身 15 分钟 + 五公里 + 放松 10 分钟）",
    "planned_distance_km": 4.8,
    "planned_duration_min": 25,
    "planned_pace_text": null,
    "planned_pace_seconds_per_km": null,
    "planned_rpe": 7,
    "purpose": "受控五公里测试",
    "warmup": "慢跑 10–15 分钟 + 动态活动，确认无疼痛后再进入主训练。",
    "main_set": "热身 15 分钟 + 五公里 + 放松 10 分钟；配速/RPE：前 2 km 控制，后 3 km 渐进；目标不是拼命，而是评估。 注意：理想接近 21:45–22:15；若更慢也不许赌命冲",
    "cooldown": "慢跑或步行放松 8–10 分钟 + 小腿、髋部轻柔拉伸。",
    "strength_training": false,
    "notes": "来源：专项训练总方案；周目标 42–46 km；原始距离/时间：热身 15 分钟 + 五公里 + 放松 10 分钟；原始强度：前 2 km 控制，后 3 km 渐进；目标不是拼命，而是评估；力量：否；注意事项：理想接近 21:45–22:15；若更慢也不许赌命冲"
  },
  {
    "week": 8,
    "dayOffset": 55,
    "workout_type": "长距离轻松跑",
    "title": "周日｜长距离轻松跑（80 分钟）",
    "planned_distance_km": 15.3,
    "planned_duration_min": 80,
    "planned_pace_text": "5'50\"-6'20\"/km",
    "planned_pace_seconds_per_km": 365,
    "planned_rpe": 3,
    "purpose": "测试后恢复",
    "warmup": "动态热身 8–10 分钟，脚踝、髋部和小腿充分活动。",
    "main_set": "80 分钟；配速/RPE：5:50–6:20/km。 注意：若测试很硬，可缩到 70 分钟",
    "cooldown": "慢跑或步行放松 8–10 分钟 + 小腿、髋部轻柔拉伸。",
    "strength_training": false,
    "notes": "来源：专项训练总方案；周目标 42–46 km；原始距离/时间：80 分钟；原始强度：5:50–6:20/km；力量：否；注意事项：若测试很硬，可缩到 70 分钟"
  },
  {
    "week": 9,
    "dayOffset": 56,
    "workout_type": "休息",
    "title": "周一｜休息",
    "planned_distance_km": 0,
    "planned_duration_min": 0,
    "planned_pace_text": null,
    "planned_pace_seconds_per_km": null,
    "planned_rpe": 1,
    "purpose": "恢复",
    "warmup": "无跑步热身；按注意事项做活动度、步行或交叉训练。",
    "main_set": "休息；配速/RPE：按恢复状态执行。 注意：复盘第八周测试",
    "cooldown": "轻柔拉伸 5–10 分钟。",
    "strength_training": false,
    "notes": "来源：专项训练总方案；周目标 55–58 km；原始距离/时间：—；原始强度：—；力量：否；注意事项：复盘第八周测试"
  },
  {
    "week": 9,
    "dayOffset": 57,
    "workout_type": "阈值主课",
    "title": "周二｜阈值主课（15 分钟热身 + 3×2 km + 放松）",
    "planned_distance_km": 2.9,
    "planned_duration_min": 15,
    "planned_pace_text": "4'48\"-4'55\"/km",
    "planned_pace_seconds_per_km": 292,
    "planned_rpe": 7,
    "purpose": "把阈值课做成主线",
    "warmup": "慢跑 10–15 分钟 + 动态活动，确认无疼痛后再进入主训练。",
    "main_set": "15 分钟热身 + 3×2 km + 放松；配速/RPE：4:48–4:55/km，组间 2 分钟慢跑。 注意：若第八周五公里 >22:30，本课按 4:52–4:58 执行",
    "cooldown": "慢跑或步行放松 8–10 分钟 + 小腿、髋部轻柔拉伸。",
    "strength_training": false,
    "notes": "来源：专项训练总方案；周目标 55–58 km；原始距离/时间：15 分钟热身 + 3×2 km + 放松；原始强度：4:48–4:55/km，组间 2 分钟慢跑；力量：否；注意事项：若第八周五公里 >22:30，本课按 4:52–4:58 执行"
  },
  {
    "week": 9,
    "dayOffset": 58,
    "workout_type": "恢复跑",
    "title": "周三｜恢复跑（40 分钟）",
    "planned_distance_km": 7.7,
    "planned_duration_min": 40,
    "planned_pace_text": "6'00\"-6'30\"/km",
    "planned_pace_seconds_per_km": 375,
    "planned_rpe": 3,
    "purpose": "吸收刺激",
    "warmup": "动态热身 8–10 分钟，脚踝、髋部和小腿充分活动。",
    "main_set": "40 分钟；配速/RPE：6:00–6:30/km。 注意：不要被手表牵着提速",
    "cooldown": "慢跑或步行放松 8–10 分钟 + 小腿、髋部轻柔拉伸。",
    "strength_training": false,
    "notes": "来源：专项训练总方案；周目标 55–58 km；原始距离/时间：40 分钟；原始强度：6:00–6:30/km；力量：否；注意事项：不要被手表牵着提速"
  },
  {
    "week": 9,
    "dayOffset": 59,
    "workout_type": "E 轻松跑",
    "title": "周四｜E 轻松跑（55 分钟）",
    "planned_distance_km": 10.5,
    "planned_duration_min": 55,
    "planned_pace_text": "5'45\"-6'15\"/km",
    "planned_pace_seconds_per_km": 360,
    "planned_rpe": 3,
    "purpose": "跑量建设",
    "warmup": "动态热身 8–10 分钟，脚踝、髋部和小腿充分活动。",
    "main_set": "55 分钟；配速/RPE：5:45–6:15/km。 注意：结束后补碳水",
    "cooldown": "慢跑或步行放松 8–10 分钟 + 小腿、髋部轻柔拉伸。",
    "strength_training": true,
    "notes": "来源：专项训练总方案；周目标 55–58 km；原始距离/时间：55 分钟；原始强度：5:45–6:15/km；力量：力量 A 35–40 分钟；注意事项：结束后补碳水"
  },
  {
    "week": 9,
    "dayOffset": 60,
    "workout_type": "E 轻松跑 + 加速跑",
    "title": "周五｜E 轻松跑 + 加速跑（50 分钟 + 8×100 米）",
    "planned_distance_km": 9.6,
    "planned_duration_min": 50,
    "planned_pace_text": "5'45\"-6'10\"/km",
    "planned_pace_seconds_per_km": 358,
    "planned_rpe": 3,
    "purpose": "神经经济性",
    "warmup": "慢跑 10–15 分钟 + 动态活动，确认无疼痛后再进入主训练。",
    "main_set": "50 分钟 + 8×100 米；配速/RPE：5:45–6:10/km。 注意：轻快，不憋",
    "cooldown": "慢跑或步行放松 8–10 分钟 + 小腿、髋部轻柔拉伸。",
    "strength_training": false,
    "notes": "来源：专项训练总方案；周目标 55–58 km；原始距离/时间：50 分钟 + 8×100 米；原始强度：5:45–6:10/km；力量：否；注意事项：轻快，不憋"
  },
  {
    "week": 9,
    "dayOffset": 61,
    "workout_type": "恢复跑",
    "title": "周六｜恢复跑（35 分钟）",
    "planned_distance_km": 6.7,
    "planned_duration_min": 35,
    "planned_pace_text": "6'05\"-6'35\"/km",
    "planned_pace_seconds_per_km": 380,
    "planned_rpe": 3,
    "purpose": "降低累积疲劳",
    "warmup": "动态热身 8–10 分钟，脚踝、髋部和小腿充分活动。",
    "main_set": "35 分钟；配速/RPE：6:05–6:35/km。 注意：小腿动作质量优先",
    "cooldown": "慢跑或步行放松 8–10 分钟 + 小腿、髋部轻柔拉伸。",
    "strength_training": true,
    "notes": "来源：专项训练总方案；周目标 55–58 km；原始距离/时间：35 分钟；原始强度：6:05–6:35/km；力量：力量 B 25–30 分钟；注意事项：小腿动作质量优先"
  },
  {
    "week": 9,
    "dayOffset": 62,
    "workout_type": "长距离跑",
    "title": "周日｜长距离跑（100 分钟）",
    "planned_distance_km": 19.2,
    "planned_duration_min": 100,
    "planned_pace_text": null,
    "planned_pace_seconds_per_km": null,
    "planned_rpe": 3,
    "purpose": "开始做“收尾有氧”",
    "warmup": "动态热身 8–10 分钟，脚踝、髋部和小腿充分活动。",
    "main_set": "100 分钟；配速/RPE：前 80 分钟 5:45–6:10；后 20 分钟 5:15–5:25。 注意：后 20 分钟不是冲",
    "cooldown": "慢跑或步行放松 8–10 分钟 + 小腿、髋部轻柔拉伸。",
    "strength_training": false,
    "notes": "来源：专项训练总方案；周目标 55–58 km；原始距离/时间：100 分钟；原始强度：前 80 分钟 5:45–6:10；后 20 分钟 5:15–5:25；力量：否；注意事项：后 20 分钟不是冲"
  },
  {
    "week": 10,
    "dayOffset": 63,
    "workout_type": "休息",
    "title": "周一｜休息",
    "planned_distance_km": 0,
    "planned_duration_min": 0,
    "planned_pace_text": null,
    "planned_pace_seconds_per_km": null,
    "planned_rpe": 1,
    "purpose": "恢复",
    "warmup": "无跑步热身；按注意事项做活动度、步行或交叉训练。",
    "main_set": "休息；配速/RPE：按恢复状态执行。 注意：餐量别省",
    "cooldown": "轻柔拉伸 5–10 分钟。",
    "strength_training": false,
    "notes": "来源：专项训练总方案；周目标 59–62 km；原始距离/时间：—；原始强度：—；力量：否；注意事项：餐量别省"
  },
  {
    "week": 10,
    "dayOffset": 64,
    "workout_type": "巡航阈值间歇",
    "title": "周二｜巡航阈值间歇（15 分钟热身 + 5×6 分钟 + 放松）",
    "planned_distance_km": 7.8,
    "planned_duration_min": 45,
    "planned_pace_text": "4'45\"-4'52\"/km",
    "planned_pace_seconds_per_km": 288,
    "planned_rpe": 7,
    "purpose": "提高阈值总量",
    "warmup": "慢跑 10–15 分钟 + 动态活动，确认无疼痛后再进入主训练。",
    "main_set": "15 分钟热身 + 5×6 分钟 + 放松；配速/RPE：4:45–4:52/km，组间 90 秒慢跑。 注意：本课比上周更看动作稳定",
    "cooldown": "慢跑或步行放松 8–10 分钟 + 小腿、髋部轻柔拉伸。",
    "strength_training": false,
    "notes": "来源：专项训练总方案；周目标 59–62 km；原始距离/时间：15 分钟热身 + 5×6 分钟 + 放松；原始强度：4:45–4:52/km，组间 90 秒慢跑；力量：否；注意事项：本课比上周更看动作稳定"
  },
  {
    "week": 10,
    "dayOffset": 65,
    "workout_type": "恢复跑",
    "title": "周三｜恢复跑（45 分钟）",
    "planned_distance_km": 7.8,
    "planned_duration_min": 45,
    "planned_pace_text": "6'00\"-6'30\"/km",
    "planned_pace_seconds_per_km": 375,
    "planned_rpe": 3,
    "purpose": "恢复",
    "warmup": "动态热身 8–10 分钟，脚踝、髋部和小腿充分活动。",
    "main_set": "45 分钟；配速/RPE：6:00–6:30/km。 注意：真正慢",
    "cooldown": "慢跑或步行放松 8–10 分钟 + 小腿、髋部轻柔拉伸。",
    "strength_training": false,
    "notes": "来源：专项训练总方案；周目标 59–62 km；原始距离/时间：45 分钟；原始强度：6:00–6:30/km；力量：否；注意事项：真正慢"
  },
  {
    "week": 10,
    "dayOffset": 66,
    "workout_type": "E 轻松跑",
    "title": "周四｜E 轻松跑（60 分钟）",
    "planned_distance_km": 10.4,
    "planned_duration_min": 60,
    "planned_pace_text": "5'45\"-6'15\"/km",
    "planned_pace_seconds_per_km": 360,
    "planned_rpe": 3,
    "purpose": "继续堆量",
    "warmup": "动态热身 8–10 分钟，脚踝、髋部和小腿充分活动。",
    "main_set": "60 分钟；配速/RPE：5:45–6:15/km。 注意：下肢主项不做到力竭",
    "cooldown": "慢跑或步行放松 8–10 分钟 + 小腿、髋部轻柔拉伸。",
    "strength_training": true,
    "notes": "来源：专项训练总方案；周目标 59–62 km；原始距离/时间：60 分钟；原始强度：5:45–6:15/km；力量：力量 A 35–40 分钟；注意事项：下肢主项不做到力竭"
  },
  {
    "week": 10,
    "dayOffset": 67,
    "workout_type": "E 轻松跑",
    "title": "周五｜E 轻松跑（45 分钟）",
    "planned_distance_km": 7.8,
    "planned_duration_min": 45,
    "planned_pace_text": "5'45\"-6'15\"/km",
    "planned_pace_seconds_per_km": 360,
    "planned_rpe": 3,
    "purpose": "容量维持",
    "warmup": "动态热身 8–10 分钟，脚踝、髋部和小腿充分活动。",
    "main_set": "45 分钟；配速/RPE：5:45–6:15/km。 注意：若很累，减到 35 分钟",
    "cooldown": "慢跑或步行放松 8–10 分钟 + 小腿、髋部轻柔拉伸。",
    "strength_training": false,
    "notes": "来源：专项训练总方案；周目标 59–62 km；原始距离/时间：45 分钟；原始强度：5:45–6:15/km；力量：否；注意事项：若很累，减到 35 分钟"
  },
  {
    "week": 10,
    "dayOffset": 68,
    "workout_type": "坡跑课",
    "title": "周六｜坡跑课（热身后 8×30 秒上坡，整课约 45–50 分钟）",
    "planned_distance_km": 8.3,
    "planned_duration_min": 48,
    "planned_pace_text": null,
    "planned_pace_seconds_per_km": null,
    "planned_rpe": 8,
    "purpose": "力量输出与摆臂驱动",
    "warmup": "慢跑 10–15 分钟 + 动态活动，确认无疼痛后再进入主训练。",
    "main_set": "热身后 8×30 秒上坡，整课约 45–50 分钟；配速/RPE：上坡 RPE 8，回程慢走慢跑。 注意：上坡要稳，不允许“拼命蹬”",
    "cooldown": "慢跑或步行放松 8–10 分钟 + 小腿、髋部轻柔拉伸。",
    "strength_training": true,
    "notes": "来源：专项训练总方案；周目标 59–62 km；原始距离/时间：热身后 8×30 秒上坡，整课约 45–50 分钟；原始强度：上坡 RPE 8，回程慢走慢跑；力量：仅核心 10–15 分钟；注意事项：上坡要稳，不允许“拼命蹬”"
  },
  {
    "week": 10,
    "dayOffset": 69,
    "workout_type": "长距离跑",
    "title": "周日｜长距离跑（105 分钟）",
    "planned_distance_km": 18.3,
    "planned_duration_min": 105,
    "planned_pace_text": null,
    "planned_pace_seconds_per_km": null,
    "planned_rpe": 3,
    "purpose": "提高耐力和有氧输出",
    "warmup": "动态热身 8–10 分钟，脚踝、髋部和小腿充分活动。",
    "main_set": "105 分钟；配速/RPE：前 85 分钟 5:45–6:10；后 20 分钟 5:10–5:20。 注意：若广州闷热，后段直接按 RPE 5 跑",
    "cooldown": "慢跑或步行放松 8–10 分钟 + 小腿、髋部轻柔拉伸。",
    "strength_training": false,
    "notes": "来源：专项训练总方案；周目标 59–62 km；原始距离/时间：105 分钟；原始强度：前 85 分钟 5:45–6:10；后 20 分钟 5:10–5:20；力量：否；注意事项：若广州闷热，后段直接按 RPE 5 跑"
  },
  {
    "week": 11,
    "dayOffset": 70,
    "workout_type": "休息",
    "title": "周一｜休息",
    "planned_distance_km": 0,
    "planned_duration_min": 0,
    "planned_pace_text": null,
    "planned_pace_seconds_per_km": null,
    "planned_rpe": 1,
    "purpose": "恢复",
    "warmup": "无跑步热身；按注意事项做活动度、步行或交叉训练。",
    "main_set": "休息；配速/RPE：按恢复状态执行。 注意：晚上拉伸 10 分钟即可",
    "cooldown": "轻柔拉伸 5–10 分钟。",
    "strength_training": false,
    "notes": "来源：专项训练总方案；周目标 63–66 km；原始距离/时间：—；原始强度：—；力量：否；注意事项：晚上拉伸 10 分钟即可"
  },
  {
    "week": 11,
    "dayOffset": 71,
    "workout_type": "阈值主课",
    "title": "周二｜阈值主课（15 分钟热身 + 4×2 km + 放松）",
    "planned_distance_km": 3.0,
    "planned_duration_min": 15,
    "planned_pace_text": "4'42\"-4'48\"/km",
    "planned_pace_seconds_per_km": 285,
    "planned_rpe": 7,
    "purpose": "抬高阈值与耐受",
    "warmup": "慢跑 10–15 分钟 + 动态活动，确认无疼痛后再进入主训练。",
    "main_set": "15 分钟热身 + 4×2 km + 放松；配速/RPE：4:42–4:48/km，组间 2 分钟慢跑。 注意：若第三组动作散，第四组保守完成",
    "cooldown": "慢跑或步行放松 8–10 分钟 + 小腿、髋部轻柔拉伸。",
    "strength_training": false,
    "notes": "来源：专项训练总方案；周目标 63–66 km；原始距离/时间：15 分钟热身 + 4×2 km + 放松；原始强度：4:42–4:48/km，组间 2 分钟慢跑；力量：否；注意事项：若第三组动作散，第四组保守完成"
  },
  {
    "week": 11,
    "dayOffset": 72,
    "workout_type": "恢复跑",
    "title": "周三｜恢复跑（45 分钟）",
    "planned_distance_km": 8.9,
    "planned_duration_min": 45,
    "planned_pace_text": "6'00\"-6'30\"/km",
    "planned_pace_seconds_per_km": 375,
    "planned_rpe": 3,
    "purpose": "恢复吸收",
    "warmup": "动态热身 8–10 分钟，脚踝、髋部和小腿充分活动。",
    "main_set": "45 分钟；配速/RPE：6:00–6:30/km。 注意：不要被同伴带快",
    "cooldown": "慢跑或步行放松 8–10 分钟 + 小腿、髋部轻柔拉伸。",
    "strength_training": false,
    "notes": "来源：专项训练总方案；周目标 63–66 km；原始距离/时间：45 分钟；原始强度：6:00–6:30/km；力量：否；注意事项：不要被同伴带快"
  },
  {
    "week": 11,
    "dayOffset": 73,
    "workout_type": "E 轻松跑",
    "title": "周四｜E 轻松跑（60 分钟）",
    "planned_distance_km": 11.9,
    "planned_duration_min": 60,
    "planned_pace_text": "5'45\"-6'15\"/km",
    "planned_pace_seconds_per_km": 360,
    "planned_rpe": 3,
    "purpose": "容量维持",
    "warmup": "动态热身 8–10 分钟，脚踝、髋部和小腿充分活动。",
    "main_set": "60 分钟；配速/RPE：5:45–6:15/km。 注意：本周力量维持，不再加组",
    "cooldown": "慢跑或步行放松 8–10 分钟 + 小腿、髋部轻柔拉伸。",
    "strength_training": true,
    "notes": "来源：专项训练总方案；周目标 63–66 km；原始距离/时间：60 分钟；原始强度：5:45–6:15/km；力量：力量 A 35 分钟；注意事项：本周力量维持，不再加组"
  },
  {
    "week": 11,
    "dayOffset": 74,
    "workout_type": "E 轻松跑 + 加速跑",
    "title": "周五｜E 轻松跑 + 加速跑（45 分钟 + 8×100 米）",
    "planned_distance_km": 8.9,
    "planned_duration_min": 45,
    "planned_pace_text": "5'45\"-6'10\"/km",
    "planned_pace_seconds_per_km": 358,
    "planned_rpe": 3,
    "purpose": "跑姿经济性",
    "warmup": "慢跑 10–15 分钟 + 动态活动，确认无疼痛后再进入主训练。",
    "main_set": "45 分钟 + 8×100 米；配速/RPE：5:45–6:10/km。 注意：100 米后完全放松走回",
    "cooldown": "慢跑或步行放松 8–10 分钟 + 小腿、髋部轻柔拉伸。",
    "strength_training": false,
    "notes": "来源：专项训练总方案；周目标 63–66 km；原始距离/时间：45 分钟 + 8×100 米；原始强度：5:45–6:10/km；力量：否；注意事项：100 米后完全放松走回"
  },
  {
    "week": 11,
    "dayOffset": 75,
    "workout_type": "十公里能力预热",
    "title": "周六｜十公里能力预热（热身后 6×3 分钟，整课约 50 分钟）",
    "planned_distance_km": 9.9,
    "planned_duration_min": 50,
    "planned_pace_text": "4'25\"-4'35\"/km",
    "planned_pace_seconds_per_km": 270,
    "planned_rpe": 8,
    "purpose": "首次轻触十公里强度",
    "warmup": "慢跑 10–15 分钟 + 动态活动，确认无疼痛后再进入主训练。",
    "main_set": "热身后 6×3 分钟，整课约 50 分钟；配速/RPE：4:25–4:35/km，组间 2 分钟慢跑，RPE 7–8。 注意：这不是 VO₂max 课，不要跑成 4:00/km",
    "cooldown": "慢跑或步行放松 8–10 分钟 + 小腿、髋部轻柔拉伸。",
    "strength_training": true,
    "notes": "来源：专项训练总方案；周目标 63–66 km；原始距离/时间：热身后 6×3 分钟，整课约 50 分钟；原始强度：4:25–4:35/km，组间 2 分钟慢跑，RPE 7–8；力量：仅核心 10 分钟；注意事项：这不是 VO₂max 课，不要跑成 4:00/km"
  },
  {
    "week": 11,
    "dayOffset": 76,
    "workout_type": "长距离跑",
    "title": "周日｜长距离跑（110 分钟）",
    "planned_distance_km": 21.8,
    "planned_duration_min": 110,
    "planned_pace_text": null,
    "planned_pace_seconds_per_km": null,
    "planned_rpe": 3,
    "purpose": "继续提升耐力",
    "warmup": "动态热身 8–10 分钟，脚踝、髋部和小腿充分活动。",
    "main_set": "110 分钟；配速/RPE：前 85 分钟 5:45–6:10；后 25 分钟 5:10–5:20。 注意：补给开始演练：30–40 g 碳水/小时",
    "cooldown": "慢跑或步行放松 8–10 分钟 + 小腿、髋部轻柔拉伸。",
    "strength_training": false,
    "notes": "来源：专项训练总方案；周目标 63–66 km；原始距离/时间：110 分钟；原始强度：前 85 分钟 5:45–6:10；后 25 分钟 5:10–5:20；力量：否；注意事项：补给开始演练：30–40 g 碳水/小时"
  },
  {
    "week": 12,
    "dayOffset": 77,
    "workout_type": "休息",
    "title": "周一｜休息",
    "planned_distance_km": 0,
    "planned_duration_min": 0,
    "planned_pace_text": null,
    "planned_pace_seconds_per_km": null,
    "planned_rpe": 1,
    "purpose": "减量和吸收",
    "warmup": "无跑步热身；按注意事项做活动度、步行或交叉训练。",
    "main_set": "休息；配速/RPE：按恢复状态执行。 注意：不额外补课",
    "cooldown": "轻柔拉伸 5–10 分钟。",
    "strength_training": false,
    "notes": "来源：专项训练总方案；周目标 50–55 km；原始距离/时间：—；原始强度：—；力量：否；注意事项：不额外补课"
  },
  {
    "week": 12,
    "dayOffset": 78,
    "workout_type": "阈值锐化",
    "title": "周二｜阈值锐化（15 分钟热身 + 4×5 分钟 + 放松）",
    "planned_distance_km": 7.7,
    "planned_duration_min": 35,
    "planned_pace_text": "4'42\"-4'48\"/km",
    "planned_pace_seconds_per_km": 285,
    "planned_rpe": 7,
    "purpose": "保持阈值感觉",
    "warmup": "慢跑 10–15 分钟 + 动态活动，确认无疼痛后再进入主训练。",
    "main_set": "15 分钟热身 + 4×5 分钟 + 放松；配速/RPE：4:42–4:48/km，组间 90 秒慢跑。 注意：结束时应感觉“锐”而不“废”",
    "cooldown": "慢跑或步行放松 8–10 分钟 + 小腿、髋部轻柔拉伸。",
    "strength_training": false,
    "notes": "来源：专项训练总方案；周目标 50–55 km；原始距离/时间：15 分钟热身 + 4×5 分钟 + 放松；原始强度：4:42–4:48/km，组间 90 秒慢跑；力量：否；注意事项：结束时应感觉“锐”而不“废”"
  },
  {
    "week": 12,
    "dayOffset": 79,
    "workout_type": "恢复跑",
    "title": "周三｜恢复跑（40 分钟）",
    "planned_distance_km": 8.8,
    "planned_duration_min": 40,
    "planned_pace_text": "6'00\"-6'30\"/km",
    "planned_pace_seconds_per_km": 375,
    "planned_rpe": 3,
    "purpose": "恢复",
    "warmup": "动态热身 8–10 分钟，脚踝、髋部和小腿充分活动。",
    "main_set": "40 分钟；配速/RPE：6:00–6:30/km。 注意：晚上早点睡",
    "cooldown": "慢跑或步行放松 8–10 分钟 + 小腿、髋部轻柔拉伸。",
    "strength_training": false,
    "notes": "来源：专项训练总方案；周目标 50–55 km；原始距离/时间：40 分钟；原始强度：6:00–6:30/km；力量：否；注意事项：晚上早点睡"
  },
  {
    "week": 12,
    "dayOffset": 80,
    "workout_type": "E 轻松跑",
    "title": "周四｜E 轻松跑（50 分钟）",
    "planned_distance_km": 10.9,
    "planned_duration_min": 50,
    "planned_pace_text": "5'45\"-6'15\"/km",
    "planned_pace_seconds_per_km": 360,
    "planned_rpe": 3,
    "purpose": "保持频率",
    "warmup": "动态热身 8–10 分钟，脚踝、髋部和小腿充分活动。",
    "main_set": "50 分钟；配速/RPE：5:45–6:15/km。 注意：所有主项减组减重",
    "cooldown": "慢跑或步行放松 8–10 分钟 + 小腿、髋部轻柔拉伸。",
    "strength_training": true,
    "notes": "来源：专项训练总方案；周目标 50–55 km；原始距离/时间：50 分钟；原始强度：5:45–6:15/km；力量：力量 A 轻版 20–25 分钟；注意事项：所有主项减组减重"
  },
  {
    "week": 12,
    "dayOffset": 81,
    "workout_type": "E 很轻松 + 4×100 米",
    "title": "周五｜E 很轻松 + 4×100 米（30 分钟）",
    "planned_distance_km": 0,
    "planned_duration_min": 30,
    "planned_pace_text": "6'00\"-6'25\"/km",
    "planned_pace_seconds_per_km": 372,
    "planned_rpe": 1,
    "purpose": "唤醒",
    "warmup": "无跑步热身；按注意事项做活动度、步行或交叉训练。",
    "main_set": "30 分钟；配速/RPE：6:00–6:25/km。 注意：不求训练效果，只求脚感",
    "cooldown": "轻柔拉伸 5–10 分钟。",
    "strength_training": false,
    "notes": "来源：专项训练总方案；周目标 50–55 km；原始距离/时间：30 分钟；原始强度：6:00–6:25/km；力量：否；注意事项：不求训练效果，只求脚感"
  },
  {
    "week": 12,
    "dayOffset": 82,
    "workout_type": "五公里正式测试",
    "title": "周六｜五公里正式测试（热身 15 分钟 + 五公里 + 放松 10–15 分钟）",
    "planned_distance_km": 5.9,
    "planned_duration_min": 27,
    "planned_pace_text": null,
    "planned_pace_seconds_per_km": null,
    "planned_rpe": 7,
    "purpose": "十二周关键门槛",
    "warmup": "慢跑 10–15 分钟 + 动态活动，确认无疼痛后再进入主训练。",
    "main_set": "热身 15 分钟 + 五公里 + 放松 10–15 分钟；配速/RPE：争取均匀配速，前 2 km 克制，后 3 km 逐步顶上去。 注意：理想接近 20:30–20:50；若 20:50–21:15 仍可推进，但需延长阈值期",
    "cooldown": "慢跑或步行放松 8–10 分钟 + 小腿、髋部轻柔拉伸。",
    "strength_training": false,
    "notes": "来源：专项训练总方案；周目标 50–55 km；原始距离/时间：热身 15 分钟 + 五公里 + 放松 10–15 分钟；原始强度：争取均匀配速，前 2 km 克制，后 3 km 逐步顶上去；力量：否；注意事项：理想接近 20:30–20:50；若 20:50–21:15 仍可推进，但需延长阈值期"
  },
  {
    "week": 12,
    "dayOffset": 83,
    "workout_type": "长距离轻松跑",
    "title": "周日｜长距离轻松跑（85–90 分钟）",
    "planned_distance_km": 19.2,
    "planned_duration_min": 88,
    "planned_pace_text": "5'50\"-6'20\"/km",
    "planned_pace_seconds_per_km": 365,
    "planned_rpe": 3,
    "purpose": "测试后的恢复耐力",
    "warmup": "动态热身 8–10 分钟，脚踝、髋部和小腿充分活动。",
    "main_set": "85–90 分钟；配速/RPE：5:50–6:20/km。 注意：若测试拼得太凶，可缩到 75–80 分钟",
    "cooldown": "慢跑或步行放松 8–10 分钟 + 小腿、髋部轻柔拉伸。",
    "strength_training": false,
    "notes": "来源：专项训练总方案；周目标 50–55 km；原始距离/时间：85–90 分钟；原始强度：5:50–6:20/km；力量：否；注意事项：若测试拼得太凶，可缩到 75–80 分钟"
  }
];
