import "server-only";
import { createHmac, createHash, timingSafeEqual } from "node:crypto";
import { getRequiredEnv } from "@/lib/env";

export const ACCESS_COOKIE_NAME = "hm_access";
export const ACCESS_COOKIE_MAX_AGE_SECONDS = 60 * 60 * 24 * 30;

type AccessTokenPayload = {
  v: 1;
  iat: number;
  exp: number;
};

function base64Url(input: string | Buffer) {
  return Buffer.from(input).toString("base64url");
}

function decodeBase64Url(input: string) {
  return Buffer.from(input, "base64url").toString("utf8");
}

export function sha256Hex(input: string) {
  return createHash("sha256").update(input, "utf8").digest("hex");
}

function normalizeSha256Hash(hash: string) {
  const trimmed = hash.trim();
  return trimmed.startsWith("sha256:") ? trimmed.slice("sha256:".length) : trimmed;
}

function safeEqualHex(a: string, b: string) {
  const left = Buffer.from(a, "hex");
  const right = Buffer.from(b, "hex");
  if (left.length !== right.length) return false;
  return timingSafeEqual(left, right);
}

export function verifyAccessCode(accessCode: string, configuredHash = getRequiredEnv("APP_ACCESS_CODE_HASH")) {
  const expectedHash = normalizeSha256Hash(configuredHash);
  if (!/^[a-f0-9]{64}$/i.test(expectedHash)) {
    throw new Error("APP_ACCESS_CODE_HASH must be a sha256 hash generated by pnpm access:hash");
  }
  const actualHash = sha256Hex(accessCode);
  return safeEqualHex(actualHash, expectedHash);
}

function sign(payloadBase64: string, secret = getRequiredEnv("APP_ACCESS_CODE_HASH")) {
  return createHmac("sha256", secret).update(payloadBase64).digest("base64url");
}

export function createAccessToken(now = Date.now()) {
  const payload: AccessTokenPayload = {
    v: 1,
    iat: now,
    exp: now + ACCESS_COOKIE_MAX_AGE_SECONDS * 1000,
  };
  const payloadBase64 = base64Url(JSON.stringify(payload));
  return `${payloadBase64}.${sign(payloadBase64)}`;
}

export function validateAccessToken(token: string | undefined, now = Date.now()) {
  if (!token) return false;
  const [payloadBase64, signature] = token.split(".");
  if (!payloadBase64 || !signature) return false;
  const expected = sign(payloadBase64);
  const expectedBuffer = Buffer.from(expected, "base64url");
  const actualBuffer = Buffer.from(signature, "base64url");
  if (expectedBuffer.length !== actualBuffer.length || !timingSafeEqual(expectedBuffer, actualBuffer)) return false;

  try {
    const payload = JSON.parse(decodeBase64Url(payloadBase64)) as AccessTokenPayload;
    return payload.v === 1 && typeof payload.exp === "number" && payload.exp > now;
  } catch {
    return false;
  }
}

export function getCookieSecurityOptions() {
  return {
    httpOnly: true,
    secure: process.env.ALLOW_INSECURE_DEV_COOKIE === "true" ? false : true,
    sameSite: "lax" as const,
    path: "/",
    maxAge: ACCESS_COOKIE_MAX_AGE_SECONDS,
  };
}
